### PR TITLE
Fix #821 - Switch to correct package eudev to fix usb service

### LINKED ISSUE #821: usb-service - docker - udev
node serialport not working anymore

https://community.gladysassistant.com/t/zwave-stick-non-detecte-dans-gladys-4/5031/80?u=vonox

### PR DESCRIPTION
**Pull request by VonOx**
https://wiki.gentoo.org/wiki/Project:Eudev

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Did you test this image ? I don't understand how this will work, because as the package installed are removed by ` apk del .build-deps` just after, will this work? (maybe yes, just asking before merging! :D)

**Comment by VonOx** [comment]
No no don't merge this, I will request approve when this PR is ready 😉
( forgot WIP in title sorry)

**Comment by VonOx** [comment]
So finally builded and tested this DockerFile

OZW , server are building fine
And node serial is working with eudev.

This PR can be merged

[pastebin build log](https://pastebin.com/tHcL24ex)

**Comment by Pierre-Gilles** [comment]
Du coup c'est quoi la conclusion sur cette PR ? :)

**Comment by VonOx** [comment]
Que ça fonctionne et que tu peux merge

**Pull request merged**
