### PR TITLE
Zwave js

### PR DESCRIPTION
**Pull request by rpochet**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Replace openzwave by zwavejs library

### CODE REVIEW

**Comment by atrovato** [comment]
Hi @rpochet,
we are interested by this feature.

Do you plan to continue to work on it?
Do you need help?

Feel free to ask for.

**Comment by rpochet** [comment]
> Hi @rpochet, we are interested by this feature.
> 
> Do you plan to continue to work on it? Do you need help?
> 
> Feel free to ask for.

Hi @atrovato 

The main issue now is to validate dev with more devices. I tried to create a docker image to deploy in my prod environment but no luck with Github, bluetooth tests failures. I also had to clean up my PR due to mismatch with another PR.... But I will continue to work on it ;-) 

I just saw that Cypress test failure on bluetooth is under investigation.

**Comment by atrovato** [comment]
I just checkout you branch, and there is many changes on calendar and scene features.
I'm not sure this is related.

Bluetooth Cypress tests are skipped for now (this PR gives a fix https://github.com/GladysAssistant/Gladys/pull/1252 - not ready to merge yet).

And now zwave-js lib is at 8.7.5 (not 8.5.0).

Feel free to ask for any help, I'm quite aware about Bluetooth / Cypress or other features, I can (try to) help.
But I have no ZWave device to test it in live mode.

**Comment by rpochet** [comment]
Indeed, I merged all branches together to create my docker image, bad idea... I reverted everything (new master and feature branch) and use a new dev branch to create my docker image. How do I synchronize my PR with my feature branch?

**Comment by atrovato** [comment]
Do you already merged all features in a single branch?
Did you keep your "only zwave" branch?

What I suggest:
```bash
# Go on you "only zwave branch"
git checkout only-zwave-branch

# Get official Gladys last changes
# According that "upstream" remote repository refers to official Gladys Git repository
git fetch upstream

# Then rebase your "only zwave" branch on last Gladys changes
git rebase upstream/master
```
You should have no conflicts 🤞 

If you are lost on this, I can create a cleaned branch based on this branch to get only zwave changes and share it with you.

**Comment by atrovato** [comment]
@rpochet here is the cleaned branch https://github.com/atrovato/Gladys/pull/29

You can checkout this branch directly from my repo to yours.

```
# Define atrovato repo
git remote add atrovato https://github.com/atrovato/Gladys.git

# Fetch remote repo
git fetch atrovato

# Clone branch
git checkout -b zwave-js-only atrovato/zwave-js

# Push clean branch
git push --set-upstream origin zwave-js-only
```

**Comment by atrovato** [comment]
On my side, Cypress fails because server won't start.
And server tests are failing too.

**Comment by atrovato** [comment]
Hi, do you feel confident on this part?
I can help if needed ;)

**Comment by rpochet** [comment]
> Hi, do you feel confident on this part? I can help if needed ;)

I have issue with USB on my dev environment (Ubuntu on Virtual Box), so unable to do real test anymore. So I finally managed to successfully create test cases. What is missing now, is use cases. So I would like to do is to use the backup file of my zwave2mqtt as input for my tests.

**Comment by rpochet** [comment]
Hi,

One server test is failing 'zwave.test.js' but it is in success locally. Git is in sync. Any advice?

PS: Cypress tests are also in error due to Bluetooth issue

**Comment by atrovato** [comment]
It looks like there is a conflict between bluetooth/noble libusb and zwave-js libusb.
I try to upgrade bluetooth dependency to fix it.
I'll keep you in touch.

But I think you have to many changed files, maybe you have troubles with git rebase - I found less than 50 changes according to zwave upgrade.

**Comment by atrovato** [comment]
In fact, this is not due to Bluetooth library, but zwave-js loads some "promise library" (@sentry/utils) which handles promise rejections and overrides default expected behavior.

**Comment by Pierre-Gilles** [comment]
@atrovato What would be the fix for the ZWaveJS promise issue ? Maybe to create an issue on ZWaveJS repo ? 

I can do it if you want, but I need the exact issue with details :)

**Comment by atrovato** [comment]
I switch to french.

Lorsque le service Bluetooth ne démarre pas à cause du matériel non disponible (tests Cypress), cela empêchait Gladys de démarrer à cause d'erreurs `uncaughtException` ou `unhandledRejection` (cf. https://github.com/GladysAssistant/Gladys/blob/cd4111253759bd520fb5830d49d4bd2e26d3a3a2/server/index.js#L14).

Hors la librairie `zwave-js` tire une dépendance qui surcharge les Promise (@sentry/utils), et les erreurs précédemment citées ne sont plus remontées.

Cette dépendance change le comportement des Promise, je ne dis ni en bien, ni en mal, mais on risquerait d'avoir d'autres comportements modifiés, et effets de bord non maîtrisés.

Maintenant la librairie `zwave-js` évolue très vite, donc en effet, il est potentiellement possible d'évoquer le problème sur le repo Github, voire même qu'il soit déjà corrigé.

**Comment by Pierre-Gilles** [comment]
> Cette dépendance change le comportement des Promise, je ne dis ni en bien, ni en mal, mais on risquerait d'avoir d'autres comportements modifiés, et effets de bord non maîtrisés.

Ok très clair, de manière générale, une librairie ne doit pas polluer le scope global, donc ce n'est pas un bon changement. 

Je vais mettre un message sur la lib ZWaveJS.

Juste pour confirmer : 

- Ce comportement apparait bien en production lors d'un simple: 

```
// Les promise sont ok
const ZwaveJS = require('zwave-js');
// les promises ont été remplacées
```

?

Je vais essayer de faire un exemple en one line pour que ça soit parlant

**Comment by Pierre-Gilles** [comment]
J'arrive à reproduire le bug localement dans Gladys, simplement en remplaçant dans le fichier 

```
server/services/bluetooth/lib/commands/bluetooth.start.js
```

J'ajoute un ` throw new Error('UNABLE TO START BLUETOOTH');` au début du start et Gladys crash, au lieu de juste retomber sur ces pattes comme c'était le cas avant (j'ai fais le test avec/sans zwave-js)

**Comment by Pierre-Gilles** [comment]
I posted an issue here: 

https://github.com/zwave-js/node-zwave-js/issues/4272

Let me know if it's not enough

**Comment by rpochet** [comment]
Bonjour,

J'ai enfin un VSC qui fonctionne!!! J'ai installé la version 14.16.0 de NodeJS (au lieu de 14.19.0).

1. ZWave désactivé
`
2022-02-22T10:19:24+0100 <error> index.js:20 (process.<anonymous>) uncaughtException catched: uncaughtException
2022-02-22T10:19:24+0100 <error> index.js:21 (process.<anonymous>) Error: ENODEV, No such device
    at Hci.init (/home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
`
image


2. ZWave activé (dernière version 8.11.6)
`
2022-02-22T10:37:44+0100 <error> index.js:20 (process.<anonymous>) uncaughtException catched: uncaughtException
2022-02-22T10:37:46+0100 <error> index.js:21 (process.<anonymous>) Error: ENODEV, No such device
    at Hci.init (/home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 19,
  code: 'ENODEV',
  syscall: 'bind'
}
Error: ENODEV, No such device
    at Hci.init (/home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:78:13)
    at /home/rpochet/Public/Gladys/server/services/bluetooth/node_modules/@abandonware/noble/lib/noble.js:60:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
`
PS: 2 fois le log de l'erreur.

image

On peut voir que la stack n'est pas la même dans les 2 cas.  En effet, Zwave utilise aussi indirectement le module signal-exit probablement pour effectuer du "nettoyage", ce qui semble être la finalité de cet événement [NodeJS uncaughtException](https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly. Le module signal-exit est une dependance de proper-lockfile par ex.

**Comment by Pierre-Gilles** [comment]
Nice! De ce que j'ai trouvé, c'est aussi la lib Sentry qui met un listen sur: 

```
  global.process.on('unhandledRejection', this.sendUnhandledPromise.bind(this));
```

Après Sentry c'est une lib d'analytics (error handling) qui remonte toutes les erreurs donc c'est le comportement voulu...

D'après ZwaveJS, ils remontent des telemetry grâce à Sentry (crash, device mal géré, etc...)

Pas moyen de le désactiver, le package sentry est import en haut du fichier ^^

https://github.com/getsentry/sentry-javascript/blob/4bbb553cc8f2ab6ba23302fc8e41c26ad90434c7/packages/node/src/integrations/onunhandledrejection.ts#L38

**Comment by rpochet** [comment]
> 

A mon humble avis, il faudrait essayer d'attraper l'erreur sans 'unhandledRejection' qui est a priori a éviter pour ce besoin. Par contre, je ne sais pas comment...

**Comment by Pierre-Gilles** [comment]
> A mon humble avis, il faudrait essayer d'attraper l'erreur sans 'unhandledRejection' qui est a priori a éviter pour ce besoin.

Je suis d'accord pour la partie dans Gladys, mais dans tous les cas ce que fait la lib "zwave-js" n'est pas acceptable en l'état : 

- importer des libs d'analytics par défaut
- polluer le scope global

L'erreur que l'on voit côté Bluetooth n'est qu'un symptôme du problème (d'ailleurs heureusement qu'on l'a vu!).

**Comment by Pierre-Gilles** [comment]
Answered: https://github.com/zwave-js/node-zwave-js/issues/4272#issuecomment-1047727632

**Comment by rpochet** [comment]
> > A mon humble avis, il faudrait essayer d'attraper l'erreur sans 'unhandledRejection' qui est a priori a éviter pour ce besoin.
> 
> Je suis d'accord pour la partie dans Gladys, mais dans tous les cas ce que fait la lib "zwave-js" n'est pas acceptable en l'état :
> 
> * importer des libs d'analytics par défaut
D'accord, enfin surtout des libs qui publient des informations sur l'exterieur, ce qui est contraire a la philosophie de Gladys

> * polluer le scope global
Pour clarifier mes idées:
* global.process n'est pas défini par Sentry -> pas de soucis
* Sentry rajoute un listener sur l'evenement 'unhandledRejection' comme pourrait le faire d'autres modules -> pas de soucis
* Le probleme se situe plutot dans la methode 'logAndExitProcess' qui est appelé car ils font appel à 'global.process.exit(1);' -> j'ai fait un test en mettant la ligne en commentaire et ca fonctionne. Par contre ce qui me fait peur, c'est que tous les mechanismes de cleanup ont été effectué et donc on se retrouve avec un systeme instable car on empeche le process de se détruire
* Désactiver Sentry va bien sûr résoudre notre probleme mais ce bug ne sera pas corrigé coté Sentry

> 
> L'erreur que l'on voit côté Bluetooth n'est qu'un symptôme du problème (d'ailleurs heureusement qu'on l'a vu!).
* Noble semble a voir plein de problemes de crash de process en cas de probleme (par ex. https://github.com/abandonware/noble/issues/132). La seule possibilite de les resoudre semble être de passer par l'evenement 'unhandledRejection'

**Comment by Pierre-Gilles** [comment]
> La seule possibilite de les resoudre semble être de passer par l'evenement 'unhandledRejection'

On catch déjà les `unhandledRejection`, mais Sentry override le comportement : https://github.com/GladysAssistant/Gladys/blob/master/server/index.js#L14

En revanche j'ai trouvé le bug du service Bluetooth, le problème ne vient pas de Noble, c'est de notre côté. Il manque un await ici : https://github.com/GladysAssistant/Gladys/blob/master/server/services/bluetooth/index.js#L16

La fonction bluetooth.start est async, et là comme elle est appelée sans await, forcément ça fait une unhandledRejection...

Essaie de rajouter le await, normalement ça te résoudra le problème :) 

Mais bon, ça ne résout pas le fait que ZwaveJS en l'état installe Sentry, et override notre unhandledRejection listener, ce qui est pas bon pour la stabilité de Gladys.

**Comment by rpochet** [comment]
> 

Je teste cela

Je dirais plutot que Sentry a eu "bug": il force un process exit. Il "n'override" pas notre unhandledRejection, il se rajoute a la liste des handler.

**Comment by Pierre-Gilles** [comment]
Tiens nous au courant.

Effectivement, il s'ajoute aux listeners, mais dans la pratique ça override le comportement qu'on a mis en place: éviter de crasher quand une exception est lancée.

**Comment by Pierre-Gilles** [comment]
https://github.com/zwave-js/node-zwave-js/issues/4272#issuecomment-1052116645

**Comment by Pierre-Gilles** [comment]
@rpochet Do we agree that the problem is fixed ? (with the `await` in the bluetooth section) ? 

For ZwaveJS, I think you can use a beta version with the new boolean to opt-out from Sentry: https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md#900-beta3-2022-03-05

**Comment by rpochet** [comment]
> 

Oui les tests Cypress fonctionnent avec les 2 correctifs. Dans certains cas, même avec le await, le module Noble lance des exceptions 'Error: ENODEV, No such device' (ex. dans ma VM si le device n'est pas configuré). Je repasse en mode unit tests.

**Comment by Pierre-Gilles** [comment]
> Dans certains cas, même avec le await, le module Noble lance des exceptions 'Error: ENODEV, No such device' (ex. dans ma VM si le device n'est pas configuré)

Oui c'est normal c'est une VM, mais bon tant que ça crash pas c'est good!  

Nickel, n'hésite pas si tu as d'autres points de blocage :)

**Comment by Pierre-Gilles** [comment]
Hello @rpochet ! Tout va bien sur le développement ? :)

**Comment by rpochet** [comment]
> Hello @rpochet ! Tout va bien sur le développement ? :)

Salut,

Nouveau boulot, nouveau PC donc une nouvelle installation...

Le build passe maintenant, reste quelques parties de code non couvertes par des tests...

J'ai deployé une image docker sur mon environnement de production.

1. Scan OK
2. J'integre les devices un par un, un peu plus complexe pour les sleeping device
3. Un device pas reconnu
4. Gestion de la couleur des lampes pas gérer
5. Les device binaires ont un mauvais etat initial (toujours 1)
6. Niveau UI, les device binaires demandent une double action pour fonctionner (intialement, bouton OFF, last_value = 1, premier clic -> bouton OFF, last_value = 0, device.setValue(0), second clic -> bouton ON, last_value = 1, device.setValue(1))
7. Scene pas géré (un bouton ou plusieurs boutons sur un device peut declencher un evenemment de type integer: click, double click...). Au minimum, il faudrait prévoir un evenemment ON/OFF

Voilà, en cours de test intensif

**Comment by atrovato** [comment]
J'ai récupéré du matériel zwave, je me ferai un plaisir de voir si ça fonctionne mieux avec la nouvelle version !

**Comment by rpochet** [comment]
> J'ai récupéré du matériel zwave, je me ferai un plaisir de voir si ça fonctionne mieux avec la nouvelle version !

Cool, car moi je pars sur une installation existante donc le controlleur est déjà initialisé

PS: je corrige le 'Un device pas reconnu' et 'Les device binaires ont un mauvais etat initial (toujours 1)' puis je commite

**Comment by Pierre-Gilles** [comment]
Merci pour le retour @rpochet, n'hésite pas dès que tu as besoin de review, ou des questions 

On peut se faire un appel à un moment aussi si tu veux :)

**Comment by Pierre-Gilles** [comment]
J'ai vraiment hâte de pouvoir virer Open-Zwave du code 😁 ca va grandement simplifier pas mal de choses pour tous les utilisateurs Gladys

**Comment by rpochet** [comment]
Niveau capteur (température, humidité, pression, luminosité) ça semble OK. 

Niveau actionneur, hormis le soucis d'etat initial (mauvais valeur mais aussi bug UI), ca semble OK, y compris le split des devices physiques. J'ai égelemment testé un Z-Uno à 8 sorties.
image
Le premier est le device physique qui permet par ex. d'eteindre les 2 relais en même temps, le second est le premier relais. Reste des soucis ergonomiques
image
Les seconds relais de 2 actionneurs double-sorties. Probablememnt car le tri est basé sur le nom et pas le selector.

Niveau capteur de puissance/énergie, c'est déjà plus compliqué car il y a 2 versions de la classe Meter (je les gère de la même manière mais à voir les différences tout de même). Je vois par ex. des facteurs de conversion.

Les ampoules RGB dimmable sont fonctionnelles (dimmer) mais pas la gestion de la couleur (je passe pour le moment)

Concernant les interrupteurs, ça se complique, car j'ai principalement des interrupteurs multiples ou multi-actions et là il y a 3 options :
- sceneId: 1 "feature" regroupant les différentes actions de tous les interrupteurs (ex. clic bouton 1 = 10, double-clic bouton 1 = 11, clic bouton 3 = 30....)
- scene-x: 1 "feature" pour chaque bouton (ex. clic bouton 1 = scene-1 = 10, clic bouton 1 = scene-2 = 10, double-clic bouton 1 = scene-1 = 11)
- basic: 1 "feature" ON/OFF pour chaque bouton/couple de bouton
Ces modes se configurent par le device selon la documentation du device. Il faudrait donc soit imposer un mode (et donc lequel). Malheureusement, mes devices sont dans le mode 2 (Jeedom les gère tous) donc inutilisable en l'état dans Gladys. J'ai donc tenté le split de ces devices et je me retrouve donc avec plusieurs device Gladys. Reste à tester

Niveau code, je suis pas forcément fier à 100%, ce n'étant pas mon language de prédilection ;-) Je devrais faire une revue complète avec le recul.

Pour un appel, je vais y regarder

**Comment by atrovato** [comment]
Hi, can you generate a docker image to test it please?

**Pull request closed without merging**
