### PR TITLE
Samsung SmartThings service

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If your changes modify the API (REST or Node.js), did you modify the documentation? (Documentation is based on comments in code)

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Samsung SmartThings connector

Based on: https://github.com/GladysAssistant/Gladys/pull/522
Doc PR: https://github.com/GladysAssistant/gladys-4-docs/pull/4

### CODE REVIEW

**Comment by atrovato** [comment]
Now waiting for SmartThings API support.
Some requests do not conform the official documentation.

**Comment by NickDub-old** [comment]
Fait gaffe, tu embarques du code de la #522 dans cette PR...

**Comment by atrovato** [comment]
Oui c'est normal, SmartThings a besoin de se connecter à un serveur avec de l'OAuth2, cette PR sert un peu de validateur de l'autre.

**Comment by atrovato** [comment]
Close it until oauth2-server is not fixed.

**Pull request closed without merging**
