### PR TITLE
Add MQTT container log limitation

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Add log limit on MQTT container.
I add a new service variable to track the container update.
Image : `atrovato/gladys:mqtt-log-limit`

### CODE REVIEW

**Comment by atrovato** [comment]
Sorry, I didn't have the time to test it in real life yet.

**Comment by atrovato** [comment]
I changed my choice, I use the existing service variable to know if docker file is at the latest revision.

**Comment by atrovato** [comment]
Ok, I tested it, I can see this when I `docker inspect gladys`:
```
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-size": "10m"
                }
            },
```

Works fine according to me :)

**Review by Pierre-Gilles — APPROVED** [review]
Tested on my side, works fine! Thanks for this PR 🙏

**Pull request merged**
