### PR TITLE
[CI] [Docker] Improvment

### LINKED ISSUE #1037: [CI] Discussion about Docker and CI
I open this issue to talk about CI 
Goal is to optimize/improve the way we build docker images.

I've already tested a lot before open this issue.

Today a full build take 1H 
image

Why is this so long ?
* Repeated build of the same dependencies ( OZW )
* Installation of the same npm packages again and again
* Our dockerfile is not cache efficient
--------------------------------

## Layers caching

First problem I encountered is circleci. For using layers caching we must pay for it ( I don't really understand why to be honest ).
Fir that reason, all tests and implementation will be done on Github Workflows.

### Open Zwave

To avoid building openzwave from source there is some simple solution => Multi Stage build

We take compiled binary from an already builded openzwave image. We are lucky because openzwave build their own and we can get real version tag ( not commit like today )

So OZW can now be added in your image like this:

```
# OpenZwave version 1.6.1520 
FROM chrisns/openzwave:alpine-1.6.1520 as ozw

# Just copy conf and binaries
COPY --from=ozw /usr/local/include/openzwave /usr/local/include/openzwave
COPY --from=ozw /openzwave/libopenzwave.so* /lib/
COPY --from=ozw /openzwave/config /usr/local/etc/openzwave
```
And voilà , OZW in our images without building it ( Several minutes saved here 😃 )

### node_modules

Also named by me "the tricky part" ( a lot of fail 😅 )

Even in active project like Gladys, npm deps doesn't change so much, why node_modules is not cached by docker when building ?

Simple answer, because we run npm install on the whole base code ! Cache is invalidated on each build.

Simple solution is to copy only package.json and lock file and run npm install on it, that way cache will work if no modification is commited , cache will be used by docker

After implementation, I'm able to build docker images in only 5 minutes ( for all platforms ) with change in codebase ( server and/or front )

image

----------------------------------------

There is some work to do but I need feedback from @GladysAssistant/core to know if I continue on this way or not.

PS: DockerFile for testing => https://github.com/VonOx/GLADYS_CI/blob/master/docker/Dockerfile.buildx
~~STEP 2 is not easy to maintain I know that 😉 .~~

### PR DESCRIPTION
**Pull request by VonOx**
This close #1037 
**Obviously, CircleCI will fail on this PR**

### Description of change

* Remove circleci stuff
* Updating Github workflow 
  * Cache efficient
  * Test on PR
  * Readability
  * Build on release
* Updating DockerFile
  * OZW not builded anymore ( multistage build )
  * Caching node_modules ( multistage build )

Generated images have been tested ( zWave is working :) )

Testing repo: https://github.com/VonOx/GLADYS_CI

### Before merging

1. Verify that secrets exists

* DOCKERHUB_USER
* DOCKERHUB_PASSWORD
* DOCKERHUB_REPO

2. Unfolow Gladys on CircleCI to avoid mail spam about failed build

### Workflows Informartions

* On PR , docker build will run only if this is not a draft PR. Both test over server and front will run every push.
* Codecov will not fail CI if uploading report fail
* Maximum use of official actions ( from docker org and codecov )
* Resulting test is available in actions summary, no need to check the log.

### CODE REVIEW

**Comment by VonOx** [comment]
This PR is now ready

**Comment by VonOx** [comment]
After call last night I pushed 2 new commits

1. npm ci everywhere
2. Add the ability to choose a tag and platform to build in manual workflow
image

Now PR is ready

**Comment by Pierre-Gilles** [comment]
Any idea why actions are failing ? (it's maybe just temporary)

Screenshot 2021-01-25 at 11 24 21

**Comment by VonOx** [comment]
Yeah DNS stuff , url resolve on this 40.119.46.219 on my computer.

You can relaunch the workflow and see if it works now

**Comment by Pierre-Gilles** [comment]
Still not working

I investigated, it's not a DNS issue, the file is indeed not found.

Try downloading: 

http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_237-3ubuntu10.43_amd64.deb

It's 404

**Comment by VonOx** [comment]
Ok just quick fix ( not tested on my CI repo )

apt update before install


Seems ok now:
image

**Pull request merged**
