### PR TITLE
[Z2M] Add lixee features ( numeric )

### PR DESCRIPTION
**Pull request by VonOx**
Need #1479 

Map features from lixee tic 
https://www.zigbee2mqtt.io/devices/ZLinky_TIC.html

image

### CODE REVIEW

**Comment by VonOx** [comment]
@atrovato I'm wrong with this PR ? Not working on my setup

Gladys keep spamming
`(Zigbee2mqttManager.handleMqttMessage) Zigbee2mqtt device Lixee TIC not configured in Gladys.`

Device state
```json
{
    "active_enerfy_out_d01": 7642,
    "active_enerfy_out_d02": 10324,
    "active_enerfy_out_d03": 4065,
    "active_enerfy_out_d04": 5516,
    "active_power": 1896,
    "active_power_max": 2160,
    "active_power_ph_b": 510,
    "apparent_power": 449,
    "available_power": 6,
    "average_rms_voltage_meas_period": 231,
    "current_date": "E220329151207",
    "current_index_tarif": 2,
    "current_price": "HEURE PLEINE",
    "current_summ_delivered": 27546,
    "current_tarif": "H PLEINE/CREUSE",
    "current_tier10_summ_delivered": 0,
    "current_tier1_summ_delivered": 11706,
    "current_tier2_summ_delivered": 15839,
    "current_tier3_summ_delivered": 0,
    "current_tier4_summ_delivered": 0,
    "current_tier5_summ_delivered": 0,
    "current_tier6_summ_delivered": 0,
    "current_tier7_summ_delivered": 0,
    "current_tier8_summ_delivered": 0,
    "current_tier9_summ_delivered": 0,
    "days_number_current_calendar": null,
    "days_number_next_calendar": null,
    "days_profile_current_calendar": null,
    "days_profile_next_calendar": null,
    "device": {
        "applicationVersion": 4,
        "dateCode": "20220217",
        "friendlyName": "Lixee TIC",
        "hardwareVersion": 1,
        "ieeeAddr": "0x00158d0005d29aa0",
        "manufacturerID": 4151,
        "manufacturerName": "LiXee",
        "model": "ZLinky_TIC",
        "networkAddress": 32871,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "4000-0005",
        "stackVersion": 2,
        "type": "Router",
        "zclVersion": 3
    },
    "drawn_v_a_max_n1": 4430,
    "elapsed": 2134,
    "last_seen": "2022-03-29T13:12:12+00:00",
    "linkquality": 69,
    "message1": "PAS DE MESSAGE",
    "message2": "",
    "meter_serial_number": "XXXXXXXXX",
    "power_threshold": 6,
    "relais": 1,
    "rms_current": 2,
    "rms_voltage": 233,
    "site_id": "XXXXXXXXXX",
    "software_revision": 2,
    "start_mobile_point1": null,
    "start_mobile_point2": null,
    "start_mobile_point3": null,
    "status_register": "003AC401",
    "stop_mobile_point1": null,
    "stop_mobile_point2": null,
    "stop_mobile_point3": null,
    "update": {
        "state": "idle"
    },
    "update_available": false
}
```

**Comment by atrovato** [comment]
@VonOx do you have to MQTT message with all exposes?

**Comment by VonOx** [comment]
This is zigbee2mqtt/bridge/devices for Lixee TIC

If mapping is based on name and not property I'm wrong

eg: I've mapped property 'current_summ_delivered' but I need to use the name 'EAST' instead , right ?

```json
{
    "date_code": "20220217",
    "definition": {
      "description": "Lixee ZLinky",
      "exposes": [
        {
          "access": 1,
          "description": "Serial Number",
          "name": "ADSC",
          "property": "meter_serial_number",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Supplier pricing schedule name",
          "name": "NGTF",
          "property": "current_tarif",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Current supplier price label",
          "name": "LTARF",
          "property": "current_price",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Current tariff index number",
          "name": "NTARF",
          "property": "current_index_tarif",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Customer tele-information protocol version",
          "name": "VTIC",
          "property": "software_revision",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Current date and time",
          "name": "DATE",
          "property": "current_date",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Total active power delivered",
          "name": "EAST",
          "property": "current_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 01)",
          "name": "EASF01",
          "property": "current_tier1_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 02)",
          "name": "EASF02",
          "property": "current_tier2_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 03)",
          "name": "EASF03",
          "property": "current_tier3_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 04)",
          "name": "EASF04",
          "property": "current_tier4_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 05)",
          "name": "EASF05",
          "property": "current_tier5_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 06)",
          "name": "EASF06",
          "property": "current_tier6_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 07)",
          "name": "EASF07",
          "property": "current_tier7_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 08)",
          "name": "EASF08",
          "property": "current_tier8_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 09)",
          "name": "EASF09",
          "property": "current_tier9_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Total provider active power delivered (index 10)",
          "name": "EASF10",
          "property": "current_tier10_summ_delivered",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Active energy withdrawn Distributor (index 01)",
          "name": "EASD01",
          "property": "active_enerfy_out_d01",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Active energy withdrawn Distributor (index 02)",
          "name": "EASD02",
          "property": "active_enerfy_out_d02",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Active energy withdrawn Distributor (index 03)",
          "name": "EASD03",
          "property": "active_enerfy_out_d03",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "Active energy withdrawn Distributor (index 04)",
          "name": "EASD04",
          "property": "active_enerfy_out_d04",
          "type": "numeric",
          "unit": "kWh"
        },
        {
          "access": 1,
          "description": "RMS current",
          "name": "IRMS1",
          "property": "rms_current",
          "type": "numeric",
          "unit": "A"
        },
        {
          "access": 1,
          "description": "RMS voltage",
          "name": "URMS1",
          "property": "rms_voltage",
          "type": "numeric",
          "unit": "V"
        },
        {
          "access": 1,
          "description": "Apparent power of reference",
          "name": "PREF",
          "property": "available_power",
          "type": "numeric",
          "unit": "kVA"
        },
        {
          "access": 1,
          "description": "Register of Statutes",
          "name": "STGE",
          "property": "status_register",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Apparent power threshold",
          "name": "PCOUP",
          "property": "power_threshold",
          "type": "numeric",
          "unit": "kVA"
        },
        {
          "access": 1,
          "description": "Current point of the active load curve drawn",
          "name": "CCASN",
          "property": "active_power",
          "type": "numeric",
          "unit": "W"
        },
        {
          "access": 1,
          "description": "Previous point of the active load curve drawn",
          "name": "CCASN-1",
          "property": "active_power_ph_b",
          "type": "numeric",
          "unit": "W"
        },
        {
          "access": 1,
          "description": "Average RMS voltage (phase 1)",
          "name": "UMOY1",
          "property": "average_rms_voltage_meas_period",
          "type": "numeric",
          "unit": "V"
        },
        {
          "access": 1,
          "description": "Immediate apparent power delivered",
          "name": "SINSTS",
          "property": "apparent_power",
          "type": "numeric",
          "unit": "VA"
        },
        {
          "access": 1,
          "description": "Apparent power delivered peak",
          "name": "SMAXN",
          "property": "active_power_max",
          "type": "numeric",
          "unit": "VA"
        },
        {
          "access": 1,
          "description": "Apparent power max. draw-off n-1",
          "name": "SMAXN-1",
          "property": "drawn_v_a_max_n1",
          "type": "numeric",
          "unit": "VA"
        },
        {
          "access": 1,
          "description": "Message short",
          "name": "MSG1",
          "property": "message1",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Message ultra-short",
          "name": "MSG2",
          "property": "message2",
          "type": "text"
        },
        {
          "access": 1,
          "description": "PRM number",
          "name": "PRM",
          "property": "site_id",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Start mobile point 1",
          "name": "DPM1",
          "property": "start_mobile_point1",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Stop mobile point 1",
          "name": "FPM1",
          "property": "stop_mobile_point1",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Start mobile point 2",
          "name": "DPM2",
          "property": "start_mobile_point2",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Stop mobile point 2",
          "name": "FPM2",
          "property": "stop_mobile_point2",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Start mobile point 3",
          "name": "DPM3",
          "property": "start_mobile_point3",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Stop mobile point 3",
          "name": "FPM3",
          "property": "stop_mobile_point3",
          "type": "numeric"
        },
        {
          "access": 1,
          "name": "RELAIS",
          "property": "relais",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Current day number supplier calendar",
          "name": "NJOURF",
          "property": "days_number_current_calendar",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Next day number supplier calendar",
          "name": "NJOURF+1",
          "property": "days_number_next_calendar",
          "type": "numeric"
        },
        {
          "access": 1,
          "description": "Profile of the next supplier calendar day",
          "name": "PJOURF+1",
          "property": "days_profile_current_calendar",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Profile of the next check-in day",
          "name": "PPOINTE1",
          "property": "days_profile_next_calendar",
          "type": "text"
        },
        {
          "access": 1,
          "description": "Link quality (signal strength)",
          "name": "linkquality",
          "property": "linkquality",
          "type": "numeric",
          "unit": "lqi",
          "value_max": 255,
          "value_min": 0
        }
      ],
      "model": "ZLinky_TIC",
      "options": [
        {
          "access": 2,
          "description": "This device does not support reporting electric measurements so it is polled instead. The default poll interval is 60 seconds, set to -1 to disable.",
          "name": "measurement_poll_interval",
          "property": "measurement_poll_interval",
          "type": "numeric",
          "value_min": -1
        },
        {
          "access": 2,
          "description": "Counter with TIC in mode standard or historique. May require restart (default: auto)",
          "name": "linky_mode",
          "property": "linky_mode",
          "type": "enum",
          "values": ["auto", "historique", "standard"]
        },
        {
          "access": 2,
          "description": "Power with single or three phase. May require restart (default: auto)",
          "name": "energy_phase",
          "property": "energy_phase",
          "type": "enum",
          "values": ["auto", "single_phase", "three_phase"]
        },
        {
          "access": 2,
          "description": "If you produce energy back to the grid (works ONLY when linky_mode: standard, default: auto)",
          "name": "production",
          "property": "production",
          "type": "enum",
          "values": ["auto", "true", "false"]
        },
        {
          "access": 2,
          "description": "Overrides the automatic current tarif. This option will exclude unnecesary attributes. Open a issue to support more of them. Default: auto",
          "name": "tarif",
          "property": "tarif",
          "type": "enum",
          "values": [
            "Historique - BASE",
            "Historique - HCHP",
            "Historique - EJP",
            "Historique - BBR",
            "Standard - Sem WE Mercredi",
            "Standard - Heure Pleine Heure Creuse",
            "auto"
          ]
        },
        {
          "access": 2,
          "description": "Number of digits after decimal point for kWh, takes into effect on next report of device.",
          "name": "kWh_precision",
          "property": "kWh_precision",
          "type": "numeric",
          "value_max": 3,
          "value_min": 0
        },
        {
          "access": 2,
          "description": "During the poll, request multiple exposes to the Zlinky at once for reducing Zigbee network overload. Too much request at once could exceed device limit. Requieres Z2M restart. Default: 1",
          "name": "measurement_poll_chunk",
          "property": "measurement_poll_chunk",
          "type": "numeric",
          "value_min": 1
        },
        {
          "access": 2,
          "description": "List of TIC commands to be exposed (separated by comma). Reconfigure device after change. Default: all",
          "name": "tic_command_whitelist",
          "property": "tic_command_whitelist",
          "type": "text"
        }
      ],
      "supports_ota": true,
      "vendor": "LiXee"
    },
    "endpoints": {
      "1": {
        "bindings": [
          {
            "cluster": "haElectricalMeasurement",
            "target": {
              "endpoint": 1,
              "ieee_address": "0x00124b0021b95104",
              "type": "endpoint"
            }
          },
          {
            "cluster": "seMetering",
            "target": {
              "endpoint": 1,
              "ieee_address": "0x00124b0021b95104",
              "type": "endpoint"
            }
          },
          {
            "cluster": "haMeterIdentification",
            "target": {
              "endpoint": 1,
              "ieee_address": "0x00124b0021b95104",
              "type": "endpoint"
            }
          },
          {
            "cluster": "liXeePrivate",
            "target": {
              "endpoint": 1,
              "ieee_address": "0x00124b0021b95104",
              "type": "endpoint"
            }
          }
        ],
        "clusters": {
          "input": [
            "genBasic",
            "genIdentify",
            "seMetering",
            "haElectricalMeasurement",
            "haMeterIdentification",
            "liXeePrivate"
          ],
          "output": ["genOta"]
        },
        "configured_reportings": [
          {
            "attribute": "currentSummDelivered",
            "cluster": "seMetering",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 100
          },
          {
            "attribute": "currentTier1SummDelivered",
            "cluster": "seMetering",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 100
          },
          {
            "attribute": "currentTier2SummDelivered",
            "cluster": "seMetering",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 100
          },
          {
            "attribute": "currentTier3SummDelivered",
            "cluster": "seMetering",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 100
          },
          {
            "attribute": "rmsCurrent",
            "cluster": "haElectricalMeasurement",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 1
          },
          {
            "attribute": "activePower",
            "cluster": "haElectricalMeasurement",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 1
          },
          {
            "attribute": "activePowerPhB",
            "cluster": "haElectricalMeasurement",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 1
          },
          {
            "attribute": "apparentPower",
            "cluster": "haElectricalMeasurement",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 1
          },
          {
            "attribute": "activePowerMax",
            "cluster": "haElectricalMeasurement",
            "maximum_report_interval": 900,
            "minimum_report_interval": 60,
            "reportable_change": 1
          }
        ],
        "scenes": []
      },
      "242": {
        "bindings": [],
        "clusters": { "input": ["greenPower"], "output": ["greenPower"] },
        "configured_reportings": [],
        "scenes": []
      }
    },
    "friendly_name": "Lixee TIC",
    "ieee_address": "0x00158d0005d29aa0",
    "interview_completed": true,
    "interviewing": false,
    "manufacturer": "LiXee",
    "model_id": "ZLinky_TIC\u0000",
    "network_address": 32871,
    "power_source": "Mains (single phase)",
    "software_build_id": "4000-0005",
    "supported": true,
    "type": "Router"
  }
```

**Comment by atrovato** [comment]
What a nice payload :)
A first look, there is no min max values on generated features.
But I will debug it on my local workspace asap.

**Comment by atrovato** [comment]
@VonOx 
I debug your payload by:
 - adding you device in `mqtt_devices_get.json` file
 - then play in debug mode the `handleMqttMessage.test.js` test file

What I see:
 - created device has no generated features
 - so you were not able to create it in Gladys!!

Why:
 - you have to map you features on name attribute, not on property
 - because z2m propose many preconfigured exposes, with same name, but on different properties
 - look at "Exposes" line a top of the z2m device page for mapping keys

More:
 - `DEVICE_FEATURE_CATEGORIES.ENERGY_SENSOR` doesn't exist in Gladys, so you will have feature with undefined category
 - I already set default min/max value for numeric values, so don't worry about this

Good luck ;)

**Comment by VonOx** [comment]
Thank you @atrovato

Yep energy sensor is another PR.

**Comment by VonOx** [comment]
@atrovato @Pierre-Gilles, I need your light on this device.

It's kind of working now but:

* I've a huge performance concern ( after adding device Gladys is very slow )
* docker log is literally spammed by feature not configured ( payload contain value for all contracts )

Thank you

**Comment by atrovato** [comment]
It looks that this device has a lot of features, I don't think Gladys manages all of them, that's the reason of "not managed feature".
You should have a look at the new state frequency. Maybe this device is sending new state each second, or at each power changes, which can generate a lot of data.
I didn't see if there is a configurable time limitation on it. But if yes, you may change it, but this won't be enough for Gladys integration.

**Review by atrovato — APPROVED** [review]
Looks good to me.

**Comment by Pierre-Gilles** [comment]
@atrovato Where are we on the improvements on the display of feature names for complex devices?

**Comment by atrovato** [comment]
@Pierre-Gilles Yes sir! https://github.com/atrovato/Gladys/pull/54

**Comment by Pierre-Gilles** [comment]
@VonOx I guess we can now merge this as I merged @atrovato PR 😎 Can you rebase and try if it's good ?

**Comment by VonOx** [comment]
@Pierre-Gilles I already use it every day ( prod image patched )
I just merge master

**Comment by VonOx** [comment]
@Pierre-Gilles Test fail

```
 1 failing

  1) gateway
       gateway.forwardDeviceStateToGoogleHome
         should forward an event to google home:
     Uncaught AssertError: expected fake to be called with arguments 
      at Object.fail (node_modules/sinon/lib/sinon/assert.js:106:21)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:65:16)
      at Object.assert.<computed> [as calledWith] (node_modules/sinon/lib/sinon/assert.js:91:13)
      at Timeout._onTimeout (test/lib/gateway/gateway.test.js:955:18)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by VonOx** [comment]
It's ok now

**Review by Pierre-Gilles — APPROVED** [review]

**Comment by Pierre-Gilles** [comment]
Merged! Thanks for your PR 🙏

**Comment by VonOx** [comment]
Thanks for merging 😁

**Pull request merged**
