### PR TITLE
Nevermind - Fixed some issues with PM2 on reboot

### PR DESCRIPTION
**Pull request by Molkobain**
I had 2 issues with PM2 :
- The script generated by pm2 startup was using the wrong user (root instead of pi)
- The dump file containing the applications to ressurect was set to empty by PM2 when rebooting, therefore the applications where not starting automatically when rebooting manually

So I made 2 changes to rpi-2-install.sh script.

This might need to be tested on distro others than raspbian.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Thanks for the PR ! I'll look at it this week.

**Comment by Pierre-Gilles** [comment]
Be careful, don't mix PR ! If you want to correct minor bugfix, correct in another PR :)

**Comment by Molkobain** [comment]
I konw, but when I clicked on "Create a PR" on my repo, it asked for a title (that was different than this one) and then when i submitted it was merged with the first PR. Don't know why. Is it because the previous was still open ?

**Comment by Molkobain** [comment]
I get it, I think I should have make a branch for each PR. Can't undo it unfortunately.

**Comment by Molkobain** [comment]
PR to delete as I did another one cleaner. I can't delete the PR on my side.

**Pull request closed without merging**
