### PR TITLE
[Front] Add VOC feature in badge number device (#1644)

### LINKED ISSUE #1644: Dashboard : Add a background color according to the level of COV
Refering to https://community.gladysassistant.com/t/indicateur-de-la-qualite-de-lair/7663/2?u=lmilcent

### PR DESCRIPTION
**Pull request by VonOx**
Fix #1644

Easy to merge :)

### CODE REVIEW

**Review by atrovato — APPROVED** [review]
Really easy :)

**Comment by atrovato** [comment]
@Pierre-Gilles the CloudFare link is not here.

**Comment by Pierre-Gilles** [comment]
@atrovato Yeah, in the end Cloudflare only build commits on the main repo, not on forks for security reasons.. ^^

**Review by Pierre-Gilles — APPROVED** [review]
Tested, it works perfectly ! Thanks for the PR :)

Screenshot 2022-11-14 at 14 36 41
Screenshot 2022-11-14 at 14 36 49
Screenshot 2022-11-14 at 14 37 08

**Pull request merged**
