### PR TITLE
Added German Localization

### PR DESCRIPTION
**Pull request by patrickschoebel**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to the community ([french forum](https://community.gladysassistant.com/)/[english forum](https://en-community.gladysassistant.com/)) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

This PR includes a complete German translation. Also, the language in local account creation is now been set based on `getDefaultState().user.language`.

### CODE REVIEW

**Review by Pierre-Gilles — COMMENTED** [review]
Thanks a lot for this PR! 🙏

Are you using Gladys from Germany? I'm happy to learn that we now have a user there!! 😄

Did you test this PR in real life?

**Comment by patrickschoebel** [comment]
Indeed, I'm using Gladys from Germany 😄 I really like it's end-user usability which I think is much better than other solutions.

Yes, I did test this PR in real life. It's working fine and as expected.

**Comment by Pierre-Gilles** [comment]
Very nice, thanks for contributing :) 

It's good for me to merge this, but I'm thinking about the future: how will we translate new features to german?

Right now I speak fluently both available languages (FR+EN) but German not so much (I still know a few sentences from high school but haven't speak much in the past years!!)

We could use: https://www.deepl.com/en/translator, or ChatGPT, or ask for your help if you are around

**Review by Pierre-Gilles — APPROVED** [review]

**Comment by patrickschoebel** [comment]
You are welcome! And thank you too!

I'm happy to translate new features into German. Deepl and ChatGPT also provide reasonable results but don't always give consistent translations. So if I can't work on German translations in time I think using Deepl/ChatGPT translations for the time being would work – or even leaving them untranslated. Then I would provide German translations as soon as possible.

**Comment by Pierre-Gilles** [comment]
That works for me! We'll do DeepL/ChatGPT by default and if you find any inconsistencies don't hesitate we can fix them :) 

By the way, don't hesitate to join us on the International forum: https://en-community.gladysassistant.com/

It's not very active for now, but usage there is growing!

**Pull request merged**
