### PR TITLE
Z2M Add support for smart valve

### PR DESCRIPTION
**Pull request by VonOx**
Related to => https://community.gladysassistant.com/t/vanne-zigbee2mqtt-absence-dun-parametre/7451

image

### CODE REVIEW

**Comment by atrovato** [comment]
That's a good question, I have same the problem according to your comment on the cover feature.
I keep thinking about it... I will let you know once I find the solution.

**Comment by atrovato** [comment]
@VonOx do you know how to handle this 3 states feature? In dashboard view?

> ### Timer_state (enum)
> Value can be found in the published state on the `timer_state` property. It's not possible to read (`/get`) this value. To write (`/set`) a value publish a message to topic `zigbee2mqtt/FRIENDLY_NAME/set` with payload `{"timer_state": NEW_VALUE}`. The possible values are: `disabled`, `active`, `enabled`.

You can add the mapping on `disabled`, `active`, `enabled` values in `enumType.js` file.

**Comment by VonOx** [comment]
OK got it , I was afraid of some side effect.

In front I think I will mimic your cover component.

**Comment by VonOx** [comment]
@atrovato @Pierre-Gilles 

What do you think about that ?

image
image
Color change if timer is active

**Comment by Pierre-Gilles** [comment]
@VonOx Nice! Have you tried putting the indicator on the left ?

182862163-d018b135-77a6-4d42-88c1-66fdea36dacc

**Comment by VonOx** [comment]
> @VonOx Nice! Have you tried putting the indicator on the left ?

image

Left of the button group

**Comment by Pierre-Gilles** [comment]
Looks cleaner to me! what do you think of this change?

**Comment by VonOx** [comment]
Based on your comment on #1576  => https://github.com/GladysAssistant/Gladys/pull/1576#issuecomment-1204999633

For button feedback while updating value, what about a spinner that replace the text ? ( I'm waiting for @atrovato feedback too )

**Comment by Pierre-Gilles** [comment]
Spinner inside the button could work!

**Comment by atrovato** [comment]
I'm not sure this matches the feature actions.

The definition in z2m says you can set 1 of this 3 values: `disabled`, `active`, `enabled`.

Where is the `active` value to set? Is the green icon an action button or only an indicator?
Did I miss something?

EDIT: but I prefer the 2nd try, on the left, and I like it ;)

**Comment by Pierre-Gilles** [comment]
@VonOx Is this ready for review? Tested in real life?

**Comment by VonOx** [comment]
Only in demo mode.

**Comment by Pierre-Gilles** [comment]
Ok, can you post a message here to get some testers? https://community.gladysassistant.com/t/vanne-zigbee2mqtt-absence-dun-parametre/7451/11

**Comment by VonOx** [comment]
@Pierre-Gilles there is only one user with this device, z2m stuff is not user friendly for testing. I will ask anyway.

**Comment by Pierre-Gilles** [comment]
@VonOx Let me know when you have news on this ^^

**Pull request closed without merging**
