### PR TITLE
Z2M add VOC Sensors

### PR DESCRIPTION
**Pull request by VonOx**
Adding voc sensors type to handle z2m device like

https://www.zigbee2mqtt.io/devices/VOCKQJK11LM.html
https://community.gladysassistant.com/t/fonctionnalites-air-quality-pour-xiaomi-aqara-tvoc/7352

### CODE REVIEW

**Review by Pierre-Gilles — COMMENTED** [review]
Was this PR tested by anyone ?

**Comment by VonOx** [comment]
Nope, no device on my side

I don't think user is in capacity to test.

**Comment by Lotharingie88** [comment]
Hello, 
For your information , i have sensor tvoc air quality xiaomi aqara aaqs s01 , but i don t have test area, so if i have guide i could, perhaps, try?


⁣Télécharger TypeApp pour Android ​

Le 28 juil. 2022, 15:40, à 15:40, Vincent KULAK ***@***.***> a écrit:

**Review by atrovato — APPROVED** [review]
I don't know what VOC is ;)

**Comment by VonOx** [comment]
@atrovato  Volatile Organic Compound

**Comment by Pierre-Gilles** [comment]
Ok, let's merge this then, the code looks fine & it's not critical in that case to fix later

**Pull request merged**
