### PR TITLE
Add CO feature

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~[ ] If your changes affects code, did your write the tests?~~
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- ~~[ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.~~
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Add new CO feature.

image

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
I don't understand the screenshot, isn't the CO feature displaying a value in ppm ?

**Comment by atrovato** [comment]
Unfortunatly no, it's a binay value: do I detect CO?
According to a sensitivity level.

EDIT: according to zigbee2mqtt case.

**Comment by Pierre-Gilles** [comment]
Oh ok, then we definitely need a proper icon in the UI, or just a text ("Detected"/"Not detected")

"1" or "0" is very weird :)

**Comment by atrovato** [comment]
Here a proposal (not pushed yet)

image

Green == 1
Red == 0
Gray == null

**Comment by Pierre-Gilles** [comment]
It's better but still it's not perfectly understandable at first sight if you don't know the meaning of this

And what about a green/red/grey "badge": 

```
<span class="badge badge-danger">CO detected!</span>
<span class="badge badge-success">All good</span>
<span class="badge badge-secondary">No value received</span>
```

?

**Comment by atrovato** [comment]
image

So I add a new BinaryDeviceValue component, to manage this kind of display, and a "complex" i18n feature value mapping, with type and category levels (for default cases). 

This screenshot is for default display
image

**Comment by Pierre-Gilles** [comment]
Looks way better now! Good job ! 👏

**Review by Pierre-Gilles — APPROVED** [review]
Tested locally, looks nice!

**Pull request merged**
