### PR TITLE
Integration sort

### PR DESCRIPTION
**Pull request by atrovato**
According to test on non admin user: https://github.com/GladysAssistant/Gladys/pull/1395#issuecomment-1152109985

I fixed the counters.

1st commit is same as the 1st PR.
2nd commit is the fix.

I miss to get only the length.

### CODE REVIEW

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
It seems there is a bug on first load, everytime I test it, it doesn't work on first load but only on second: 

https://user-images.githubusercontent.com/7365207/173329280-c07882b9-48b0-496d-9f9c-dd23162c6809.mov

**Comment by VonOx** [comment]
Reproduced the bug here too

**Comment by atrovato** [comment]
Thank you for feedbacks, I forgot the async on action method.
And I add the "admin system" page management too.
All should be fixed now.

**Review by Pierre-Gilles — APPROVED** [review]
Thanks for your fixes, looks fine to me!

**Pull request merged**
