### PR TITLE
Brightness device feature Dashboard

### PR DESCRIPTION
**Pull request by VonOx**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
~~- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
~~- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
~~- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

This PR add brightness slider to dashboard

image

### CODE REVIEW

**Comment by atrovato** [comment]
Nice to have, you use a simple slider, be carefull with device long names.

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Very nice PR! thanks 👏 

I tried it with the MQTT service, it works fine, except one thing, it's weird the bar is displayed all in blue ?

Screenshot 2021-03-01 at 11 46 57

It's weird because on your screenshot, it's fine.

I'm using Chrome 88

**Comment by VonOx** [comment]
Oh!

This is the same slider from multi level device. So broken too on Chrome.
Screenshot has been taken from latest Firefox.

**Comment by VonOx** [comment]
Confirmed on chrome, is this tabler related issue ?

**Comment by Pierre-Gilles** [comment]
It's probably a tabler issue, it seems to work in the latest version of tabler:

Screenshot 2021-03-01 at 18 00 48

Maybe let's find what's different between the two version and apply a patch here ?

**Comment by VonOx** [comment]
Not something as simple, in your version input is styled. Latest tabler use nouislider plugin and style are applied on div.

I let you decide what to do, but maybe this chrome behavior is something acceptable ( the slider works ). And when tabler will be updated ( a lot of work ) slider will be ok on chrome.

**Review by Pierre-Gilles — APPROVED** [review]
Ok to merge

**Pull request merged**
