### PR TITLE
issue #300 color picker

### PR DESCRIPTION
**Pull request by atrovato**
Set a color picker if device type is color.

### CODE REVIEW

**Comment by atrovato** [comment]
Merged with last device page updates (v3.9.x).

**Comment by atrovato** [comment]
Need https://github.com/GladysProject/Gladys/issues/405 to be fixed to ensure lastValue loading.

**Comment by atrovato** [comment]
Please see GUI proposal :
color-picker-sample

**Comment by MathieuAndrade** [comment]
Hey!

Good idea, but it does not work for me :confused:
The background color does not change and I have an error in logs

Here is a screenshot for more precision on the error and it comes from :smile:

image

**Comment by atrovato** [comment]
Hello,
I can't reproduce your issue, it works well by my side.

Please see steps I follow to make it work : 
  1. checkout the branch
  2. execute "grunt buildProd"
  3. execute "sails lift" for dev mode

Am I doing it right ?

**Comment by Boimb** [comment]
Not tried, but I may have a clue:
The error is a null pointer on : 
`element.css('background-color', '#' + (modelValue).toString(16));`
And it seems @MathieuAndrade just created a deviceType to test... It surely have no deviceState associated and so modelValue is undefined.
Try to avoid null on this. Maybe a default to 'ffffff' ?

**Comment by atrovato** [comment]
You're right, as there is no default value, a npe is thrown.
Now fixed.
Thank you for your help ;)

**Comment by Pierre-Gilles** [comment]
Thanks for your PR, and sorry for being late merging it! 

I just merged it, it works perfectly on my side, great job 👏👏

**Pull request closed without merging**
