### PR TITLE
Fix bluetooth cypress tests

### PR DESCRIPTION
**Pull request by atrovato**
Bluetooth Cypress tests.

Force some states before tests.

### CODE REVIEW

**Comment by atrovato** [comment]
I close until this is ready.

**Comment by atrovato** [comment]
Looks good for now.

**Comment by Pierre-Gilles** [comment]
It's quite ironic 😃

Screenshot 2021-10-09 at 16 02 28

**Comment by atrovato** [comment]
Looks not so good for now.
Failure is random, so fix is not so easy.
I take it back.

**Comment by Pierre-Gilles** [comment]
@atrovato Yes that what I was seeing on those tests too, that's why I disabled them

**Comment by atrovato** [comment]
So, on this, I rebase branch each time a PR is merged on master, I run it many, many times, Cypress tests never failed again.
It looks good for me 🤞

**Review by Pierre-Gilles — APPROVED** [review]

**Pull request merged**
