### PR TITLE
Lucid icon migration

### PR DESCRIPTION
**Pull request by VonOx**
Replace feather by lucid icon font ( v 0.16.19 )

image

1to1 replacement

Related to: https://github.com/GladysAssistant/theme-optimized/pull/1

### CODE REVIEW

**Comment by VonOx** [comment]
CI fail but build front work in local ( npm cache behavior ) 
Can anyone give it a try ? ( @atrovato @cicoub13 @Pierre-Gilles )

**Comment by Pierre-Gilles** [comment]
Nice! Great work 👏

A few questions: 

- Do all icons that existed in feather icons exists in lucid ? (I guess yes, but just asking :) )
- Are existing scenes icons in database still displayed the same way with that PR ?
- What's the bundle size difference between a Lucid & Feather build ? 
- I don't know if it's your screenshot / a CSS issue / or it's Lucid icons that are different, but there are some weird lines on top/below some icons, doesn't look as nice as before: 

142832724-0f13f9ac-0284-4303-a40f-344f82ce8dfd

- Also, the "integrations" icon is weird: 

Before:

Screenshot 2021-11-22 at 15 26 00

After: 

142832724-0f13f9ac-0284-4303-a40f-344f82ce8dfd

**Comment by VonOx** [comment]
> * Do all icons that existed in feather icons exists in lucid ? (I guess yes, but just asking :) )

Yes some with little fix, some renamed ( like grid we use for integrations )

> * Also, the "integrations" icon is weird:

Fixed same icon is `layout-grid`

> * What's the bundle size difference between a Lucid & Feather build ?

I've no idea, obviously there is a difference ( 512 icons vs 286 for feather ) 
CI check this , no ?



> * I don't know if it's your screenshot / a CSS issue / or it's Lucid icons that are different, but there are some weird lines on top/below some icons, doesn't look as nice as before:

Yep my screenshot seems weird ( will repost a new one )

**Comment by Pierre-Gilles** [comment]
> I've no idea, obviously there is a difference ( 512 icons vs 286 for feather ) CI check this , no ?

When I implemented the CI for bundle size check (RelativeCI), at the time they didn't support external PR but only internal branches on a repo, so it's not working here. ( There is an issue to fix this: https://github.com/GladysAssistant/Gladys/issues/1303 ) 

> Yep my screenshot seems weird ( will repost a new one )

Ok! Indeed it looks like a screenshot issue

**Comment by VonOx** [comment]
@Pierre-Gilles you are right it's a font/stroke problem, need to check with lucide-icons team 😐

**Comment by atrovato** [comment]
@VonOx not sure that `"@gladysassistant/theme-optimized": "VonOx/theme-optimized#lucide-migration"` can be found in CI.

**Comment by atrovato** [comment]
@VonOx I can't make it work in local, any trick ?
image

**Comment by VonOx** [comment]
Yep I noticed that, demo mode is working anyway.
Static Build still refer to feather icon ( I don't know why)

**Comment by VonOx** [comment]
@Pierre-Gilles I've replaced the screenshot ( mozilla browser with lucide icon ) , only chromium have the weird aliasing issue.

@atrovato I've added some fix, can you retry ?

Some check screenshot:

image
image
image

@Pierre-Gilles Left menu icon must be light or dark grey ?

**Comment by Pierre-Gilles** [comment]
@VonOx No idea! Let's pick the one closest to what we have actually?

Looks like this with Feather: 

Screenshot 2021-11-25 at 09 58 28

> only chromium have the weird aliasing

Any chromium based browser have the issue or only Chromium? (Chrome, Brave?)

**Comment by VonOx** [comment]
Any chromium based browser and on Windows ( no problem on Linux), can't test on mac os. Very weird.

**Comment by Pierre-Gilles** [comment]
Super weird :/ Well I guess for now good old Feather stays the most stable option 🤣

**Pull request closed without merging**
