### PR TITLE
Button click user friendly

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~[ ] If your changes affects code, did your write the tests?~~
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Override button click values by user friendly wording.

See https://community.gladysassistant.com/t/affichage-des-boutons-textuels-dans-les-scenes-et-tableau-de-bord-au-lieu-dentier/7644

#### Dashboard

image

#### Scene

image

### CODE REVIEW

**Comment by VonOx** [comment]
@Pierre-Gilles can you build front dev? I will test with gladys plus.

**Comment by Pierre-Gilles** [comment]
Great PR @atrovato ! Thanks 🙏

@VonOx Done ✅ 

You can find a build here: https://github.com/GladysAssistant/Gladys/pull/1674#issuecomment-1354250585

Ping me anytime you want a new build, I will rebase my branch ;)

**Comment by VonOx** [comment]
@atrovato I can't save a scene with this trigger

image

UI is ok

**Comment by atrovato** [comment]
I had an error on update valie method in the "button click" trigger.
Now fixed @VonOx 
And I rebase this branch with master.

**Comment by VonOx** [comment]
@atrovato state is not displayed after saving
image

If I use master codebase it is ( after saving with your PR )
image

**Comment by atrovato** [comment]
@VonOx Thank you.
I fixed it, and add this case in demo mode.

**Comment by Pierre-Gilles** [comment]
@VonOx Could you re-test on your side ? :)

**Comment by VonOx** [comment]
Yes @Pierre-Gilles I just need a test build on #1674

**Comment by Pierre-Gilles** [comment]
@VonOx Done in https://github.com/GladysAssistant/Gladys/pull/1711. Build will be ready in a few minutes.

@atrovato Could you setup front builds on your own repository so it's automatic on your PR? :) It's not very fluid if I need to manually create a PR for every commit, we lose a lot of time 😅

**Comment by VonOx** [comment]
Everything is OK, can be merged

**Comment by Pierre-Gilles** [comment]
Thanks @VonOx ! Merged

**Pull request merged**
