### PR TITLE
Fix #728 limit websocket messages

### LINKED ISSUE #728: Find a way to send camera websockets images only when user needs it in UI
Right now, camera image are sent all the time in websocket, even if the user is watching the settings page... it should not be the case!

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/gladys-4-docs) and the [website](https://documentation.gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Limit messages on websockets according to subscribed event types.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Amazing job! It's exactly what I had in mind!

**Comment by atrovato** [comment]
Nice, but I don't know why codecov failed (again).

**Comment by Pierre-Gilles** [comment]
Codecov is terrible... ^^

Same for me, I don't have codecov results working on my side

I got a 502 Bad gateway errors when sending coverage in CircleCI, I don't know why.

Screenshot 2020-04-27 at 17 27 08

We definitely need to find another tool, this one is the worse

In the meantime, I'll try to find a fix, this PR is really nice and I want to merge it!

**Comment by Pierre-Gilles** [comment]
FYI, this PR is good for me but I can't merge it right now because it'll break the Gladys Gateway integration, I need to dedicate some time to make this work with the Gladys Gateway.

**Comment by Pierre-Gilles** [comment]
I will check this, thanks for the PR again! Sorry, I completely forgot since then, there are so many open PR on this repo it's hard to keep track 😅

**Comment by Pierre-Gilles** [comment]
Not stale, not in my priority right now...

**Comment by atrovato** [comment]
Abandonned for now.

**Pull request closed without merging**
