### PR TITLE
[WIP] Zigbee2mqtt service

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If your changes modify the API (REST or Node.js), did you modify the documentation? (Documentation is based on comments in code)

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Manages zigbee2mqtt communication with devices.
And try to manage all supported devices listed at https://www.zigbee2mqtt.io/information/supported_devices.html

Based on MQTT PR #517 
Linked to documentation PR https://github.com/GladysAssistant/gladys-4-docs/pull/5

### CODE REVIEW

**Comment by atrovato** [comment]
Works well with sensors, but can't test with actuators.

**Comment by Pierre-Gilles** [comment]
Thanks for your work! This integration is huge! :)

It seems someone on the forum is happy to help testing ( https://community.gladysassistant.com/t/v4-integration-zigbee2mqtt/5009/7?u=pierre-gilles ) 

How many people tested this for now?

**Comment by atrovato** [comment]
There is a lot of compatible devices with each specific configuration. 

I'll ask for morre testing.
Currently, this is tested only with Aqara sensors and VoNox help.

I will see to add the actuator part asap.

**Comment by Pierre-Gilles** [comment]
Ok good! 

So what's the next step for this PR?

Should we merge before having the actuator part working (it can be a next PR)?

**Comment by atrovato** [comment]
I would prefer to merge this part first.
Just be careful, I changed the UI SensorBox to be "more compliant". All others are specific to this integration service.

But you are the master, you take the final decision :wink:

**Comment by Pierre-Gilles** [comment]
Hey! So what are the news on this? :) 

Did some people on the forum test it?

**Comment by atrovato** [comment]
Hi,
no people tests it more fro now, but some were just getting the device, I wait for feedbacks.

More, Reno is improving this service to add captor capacity. He forked this branch on my repo to complete it.
I think we can wait a little more to take feedbacks into account.

**Comment by atrovato** [comment]
According to [R6n0 PR](https://github.com/atrovato/Gladys/pull/1) (on my fork), some bugs are pending.
He is also working on the `setValue` feature.
I'll review and merge it when improvements are done.

**Comment by Pierre-Gilles** [comment]
Ok! 

Let me know when it's good. In the meantime, I put this PR as WIP in the title.

**Comment by atrovato** [comment]
Linked to documentation PR: https://github.com/GladysAssistant/gladys-4-docs/pull/5

**Comment by atrovato** [comment]
I close this one as @R6n0 is working on https://github.com/GladysAssistant/Gladys/pull/688

**Pull request closed without merging**
