### PR TITLE
Integration/domoticz

### PR DESCRIPTION
**Pull request by dricair**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Adds Domoticz integration, connecting to an existing Domoticz server

image

The configuration page asks for the server and port and permits connecting to the server:

image

Devices are listed and can be added. In this case they will get polled regularly:

image

### Main concerns

This is mostly to show the concept for now to get feedback as it contains some limitations:

- Need to ask for username and password when authentication are required
- Only temperature (Potentially with humidity and pressure) are supported for now.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Looks really nice!

I had a quick look at the code and it looks great too. Good job 👏 

> Need to ask for username and password when authentication are required

When do you need to ask for username & password ? At the first configuration ? Isn't there an API key mecanism in Domoticz? 

> Only temperature (Potentially with humidity and pressure) are supported for now.

It's a good start :) Any idea how hard it would be to integrate more devices?

**Comment by dricair** [comment]
The username and password is optional (Typically if Gladys and Domoticz are both running on the same Raspberry). But it's possible to have them setup and even access a remote server (In HTTPS). Username and password will be requested in the config page, with the server and port (Only once of course)

It uses basic authentication so it's easy to add:
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Authorization

I wanted to show this first version to continue, but the next step will be for devices that require an action (Switches). I wanted to add shutter control as well but I saw it's not supported in Gladys yet (At least need up/down/stop, possibly inverted).

The advantage I see for other devices is that we don't need to know the exact device but only the global category (thermometer, switch, meter, etc.) but I will be limited by the devices I have. It may be interesting to provide option to display JSON input of unsupported devices (From Domoticz) so that support can be added.

**Comment by Pierre-Gilles** [comment]
I see, that's not a big problem in my opinion for a first PR, this just need to be really clear in the UI, a message should say "right now, we only support temperature/humidity device, but we are looking for more testers to help us add more types of devices"

> It may be interesting to provide option to display JSON input of unsupported devices (From Domoticz) so that support can be added.

Yes! 

Could you do what we did for the Philips hue / Z-Wave ? We added a button for "unknown type of devices", and when you click on it, it redirects to github and automatically creates an issue with the JSON of the device. It's really handy to help people show their configuration to developers :) What do you think?

**Comment by dricair** [comment]
Ok it make sense. I will look at Philips Hue and ZWave for the Github feature.

**Comment by Pierre-Gilles** [comment]
Amazing! Let me know when it's good. I'm putting this PR in Draft while it's work in progress :)

**Comment by Pierre-Gilles** [comment]
Hey! Any news on this PR? 🙂

**Pull request closed without merging**
