### PR TITLE
Chart with light loader

### LINKED ISSUE #1490: [FRONT] - On chart dashboard box, loading spinner when new value arrives is displayed too often
image

https://community.gladysassistant.com/t/graph-bug-refresh/7108

### PR DESCRIPTION
**Pull request by atrovato**
Add a light loader bar in chart box.
This fixes #1490 
See comment https://github.com/GladysAssistant/Gladys/issues/1490#issuecomment-1116513931

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
It's a bit weird to have this bar at the bottom all the time no?

Screenshot 2022-08-04 at 11 13 14

**Comment by VonOx** [comment]
@atrovato we continue discussion here

As mentioned by @Pierre-Gilles it's worth now 😅 
image

**Comment by atrovato** [comment]
Ok I have another option, what about this?
A "soft" border blink.



Why do I change?
If we add a progress bar inside the card, we will add 3px, this will make the div bigger.
If we add this a the bottom, we will have a white bar at the chart bottom.
Here we alread have a border, so box doesn't have to be bigger, or resized.

**Comment by VonOx** [comment]
I love it. 👍

**Comment by atrovato** [comment]
@VonOx the border blink effect is ready here :)

**Comment by Pierre-Gilles** [comment]
@atrovato Amazing job it's really clean !! I love it too aha !

**Review by Pierre-Gilles — APPROVED** [review]
Looks super clean, amazing work I love it! 👏

**Pull request merged**
