### PR TITLE
Common sort/search device component

### LINKED ISSUE #1623: Device filtering kept on tab change but keyword not displayed
First, are you sure that you found a Gladys bug?

If you are not sure, you can come discuss with us on [Gladys Community](http://community.gladysassistant.com/) 🙂

**Describe the bug**
When doing device filetring on integration screen, if we move tab and go back to device tab, devices are still filtered but search keyword is not displayed

**To Reproduce**

1. Go to device tab e.g. '/dashboard/integration/device/zigbee2mqtt'
2. Set a device filtering keyword, only filtered devices are shown
3. Go to setup tab e.g. '/dashboard/integration/device/zigbee2mqtt/setup'
4. Go back to device tab e.g. '/dashboard/integration/device/zigbee2mqtt'
5. Only filtered devices are shown but filtering keyword is empty

**Expected behavior**
Going back to device tab e.g. '/dashboard/integration/device/zigbee2mqtt' should either 
1. Display all devices
2. Display previously filtered devices with the previously device filtering keyword

**Screenshots**
image
image
image
image

image

**Your Gladys installation (please complete the following information):**

- Intel NUC
- Debian docker

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome, IE
- Version: ???

**Additional context**

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Introduce a common "sort / device" component and avoid "long code duplication".

May resolve #1623

### CODE REVIEW

**Comment by atrovato** [comment]
It keeps filter value when change page and go back, it can be a patch for #1623 bug.

**Comment by atrovato** [comment]
Yeah cloudflare is setup: https://6c581e79.gladys.pages.dev/dashboard

**Comment by Pierre-Gilles** [comment]
@atrovato Your cloudflare pages is not public: 

Screenshot 2023-03-24 at 13 52 44

**Comment by atrovato** [comment]
I can't set-up public access for "preview" pages easily... I have to record a DNS or any identity provider...

**Comment by atrovato** [comment]
Or maybe: https://6c581e79.gladys.pages.dev/

**Review by Pierre-Gilles — APPROVED** [review]
Tested locally, it works fine! Good for me :)

**Comment by atrovato** [comment]
Bundle Size — 7.2MiB (-0.09%)
My idea is to make it smaller!

**Pull request merged**
