### PR TITLE
MQTT - Replace shell script by javascript functions

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Review by Pierre-Gilles — APPROVED** [review]
So good !! Thanks for this PR 🙏 

Good for me, can you provide a Docker build to test this in real life?

**Comment by atrovato** [comment]
There it is `atrovato/gladys:mqtt`.

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Ok so I tried it but it seems it doesn't work

Screenshot 2022-12-12 at 14 18 26

Gladys: 

```
2022-12-12T08:18:07+0100 <info> installContainer.js:18 (MqttHandler.installContainer) MQTT broker is being installed as Docker container...
2022-12-12T08:18:07+0100 <info> installContainer.js:22 (MqttHandler.installContainer) Check Gladys network...
2022-12-12T08:18:07+0100 <info> installContainer.js:28 (MqttHandler.installContainer) Pulling eclipse-mosquitto:2 image...
2022-12-12T08:18:08+0100 <info> installContainer.js:32 (MqttHandler.installContainer) Preparing broker environment...
2022-12-12T08:18:08+0100 <info> configureContainer.js:25 (MqttHandler.configureContainer) MQTT broker Docker container is being configured...
2022-12-12T08:18:08+0100 <info> configureContainer.js:42 (MqttHandler.configureContainer) Writting default eclipse-mosquitto configuration...
2022-12-12T08:18:08+0100 <info> installContainer.js:35 (MqttHandler.installContainer) Creating container...
2022-12-12T08:18:08+0100 <info> installContainer.js:43 (MqttHandler.installContainer) MQTT broker successfully installed as Docker container
```

Logs from Mosquitto containers: 

```
1670829515: mosquitto version 2.0.15 starting
1670829515: Config loaded from /mosquitto/config/mosquitto.conf.
1670829515: Error: Unable to open pwfile "/mosquitto/config/mosquitto.passwd".
1670829515: Error opening password file "/mosquitto/config/mosquitto.passwd".
 ````

Gladys assistant folder: 

```
/var/lib/gladysassistant/mosquitto# ls -lh
total 4.0K
-rw-r--r-- 1 1883 1883 110 Dec 12 08:18 mosquitto.conf
```

**Comment by atrovato** [comment]
The password has to be created at init phase, I was missing this point.
I fixed it, rebase branch, test it.
Looks fine now, @Pierre-Gilles 

EDIT: and publish a new image (atrovato/gladys:mqtt)

**Review by Pierre-Gilles — APPROVED** [review]
Looks good to me! Tested on a server, it works fine!

**Pull request merged**
