### PR TITLE
[philips-hue] - Add devices

### LINKED ISSUE #888: Philips Hue: Add device LCT012
```
{
  "name": "Hue color candle 1",
  "service_id": "86b98c11-f85f-44e4-8f18-030576b3ee9d",
  "external_id": "philips-hue-light:ecb5fa0a6722:5",
  "selector": "philips-hue-light:ecb5fa0a6722:5",
  "should_poll": true,
  "model": "LCT012",
  "poll_frequency": 60000,
  "features": [],
  "not_handled": true,
  "raw_philips_hue_device": {
    "_rawData": {
      "state": {
        "on": true,
        "bri": 254,
        "hue": 8402,
        "sat": 140,
        "effect": "none",
        "xy": [
          0.4575,
          0.4099
        ],
        "ct": 366,
        "alert": "none",
        "colormode": "xy",
        "mode": "homeautomation",
        "reachable": true
      },
      "swupdate": {
        "state": "noupdates",
        "lastinstall": "2020-03-03T13:31:31"
      },
      "type": "Extended color light",
      "name": "Hue color candle 1",
      "modelid": "LCT012",
      "manufacturername": "Signify Netherlands B.V.",
      "productname": "Hue color candle",
      "capabilities": {
        "certified": true,
        "control": {
          "mindimlevel": 2000,
          "maxlumen": 450,
          "colorgamuttype": "C",
          "colorgamut": [
            [
              0.6915,
              0.3083
            ],
            [
              0.17,
              0.7
            ],
            [
              0.1532,
              0.0475
            ]
          ],
          "ct": {
            "min": 153,
            "max": 500
          }
        },
        "streaming": {
          "renderer": true,
          "proxy": true
        }
      },
      "config": {
        "archetype": "candlebulb",
        "function": "mixed",
        "direction": "omnidirectional",
        "startup": {
          "mode": "safety",
          "configured": true
        }
      },
      "uniqueid": "00:17:88:01:04:44:b0:de-0b",
      "swversion": "1.50.2_r30933",
      "swconfigid": "A9AFB57A",
      "productid": "Philips-LCT012-1-E14ECLv1"
    },
    "_id": 5,
    "mappedColorGamut": "C"
  }
}
```

### LINKED ISSUE #889: Philips Hue: Add device LTG002
```
{
  "name": "Hue ambiance spot 1",
  "service_id": "86b98c11-f85f-44e4-8f18-030576b3ee9d",
  "external_id": "philips-hue-light:ecb5fa0a6722:7",
  "selector": "philips-hue-light:ecb5fa0a6722:7",
  "should_poll": true,
  "model": "LTG002",
  "poll_frequency": 60000,
  "features": [],
  "not_handled": true,
  "raw_philips_hue_device": {
    "_rawData": {
      "state": {
        "on": true,
        "bri": 254,
        "ct": 366,
        "alert": "none",
        "colormode": "ct",
        "mode": "homeautomation",
        "reachable": true
      },
      "swupdate": {
        "state": "noupdates",
        "lastinstall": "2020-05-12T12:14:48"
      },
      "type": "Color temperature light",
      "name": "Hue ambiance spot 1",
      "modelid": "LTG002",
      "manufacturername": "Signify Netherlands B.V.",
      "productname": "Hue ambiance spot",
      "capabilities": {
        "certified": true,
        "control": {
          "mindimlevel": 200,
          "maxlumen": 350,
          "ct": {
            "min": 153,
            "max": 454
          }
        },
        "streaming": {
          "renderer": false,
          "proxy": false
        }
      },
      "config": {
        "archetype": "spotbulb",
        "function": "functional",
        "direction": "downwards",
        "startup": {
          "mode": "safety",
          "configured": true
        }
      },
      "uniqueid": "00:17:88:01:06:ba:d3:6c-0b",
      "swversion": "1.65.11_hB798F2",
      "swconfigid": "EB7E2352",
      "productid": "Philips-LTG002-1-GU10CTv2"
    },
    "_id": 7
  }
}
```

### LINKED ISSUE #891: Philips Hue: Add device LWV001
```
{
  "name": "Hue filament bulb 1",
  "service_id": "86b98c11-f85f-44e4-8f18-030576b3ee9d",
  "external_id": "philips-hue-light:ecb5fa230205:4",
  "selector": "philips-hue-light:ecb5fa230205:4",
  "should_poll": true,
  "model": "LWV001",
  "poll_frequency": 60000,
  "features": [],
  "not_handled": true,
  "raw_philips_hue_device": {
    "_rawData": {
      "state": {
        "on": true,
        "bri": 1,
        "alert": "select",
        "mode": "homeautomation",
        "reachable": false
      },
      "swupdate": {
        "state": "noupdates",
        "lastinstall": "2020-04-11T12:18:47"
      },
      "type": "Dimmable light",
      "name": "Hue filament bulb 1",
      "modelid": "LWV001",
      "manufacturername": "Signify Netherlands B.V.",
      "productname": "Hue filament bulb",
      "capabilities": {
        "certified": true,
        "control": {
          "mindimlevel": 2000,
          "maxlumen": 550
        },
        "streaming": {
          "renderer": false,
          "proxy": false
        }
      },
      "config": {
        "archetype": "vintagebulb",
        "function": "decorative",
        "direction": "omnidirectional",
        "startup": {
          "mode": "safety",
          "configured": true
        }
      },
      "uniqueid": "00:17:88:01:08:9e:80:8c-0b",
      "swversion": "1.65.9_hB3217DF",
      "swconfigid": "EE0A6503",
      "productid": "Philips-LWV001-1-ST64CFDLv1"
    },
    "_id": 4
  }
}
```

### LINKED ISSUE #912: Philips Hue: Add device LTA001
```
{
  "name": "Master bedroom left",
  "service_id": "86b98c11-f85f-44e4-8f18-030576b3ee9d",
  "external_id": "philips-hue-light:ecb5fa23281a:4",
  "selector": "philips-hue-light:ecb5fa23281a:4",
  "should_poll": true,
  "model": "LTA001",
  "poll_frequency": 60000,
  "features": [],
  "not_handled": true,
  "raw_philips_hue_device": {
    "_rawData": {
      "state": {
        "on": false,
        "bri": 254,
        "ct": 443,
        "alert": "select",
        "colormode": "ct",
        "mode": "homeautomation",
        "reachable": true
      },
      "swupdate": {
        "state": "noupdates",
        "lastinstall": "2020-10-17T13:13:50"
      },
      "type": "Color temperature light",
      "name": "Master bedroom left",
      "modelid": "LTA001",
      "manufacturername": "Signify Netherlands B.V.",
      "productname": "Hue ambiance lamp",
      "capabilities": {
        "certified": true,
        "control": {
          "mindimlevel": 200,
          "maxlumen": 800,
          "ct": {
            "min": 153,
            "max": 454
          }
        },
        "streaming": {
          "renderer": false,
          "proxy": false
        }
      },
      "config": {
        "archetype": "wallshade",
        "function": "functional",
        "direction": "omnidirectional",
        "startup": {
          "mode": "safety",
          "configured": true
        }
      },
      "uniqueid": "00:17:88:01:08:ae:75:6e-0b",
      "swversion": "1.65.9_hB3217DF",
      "swconfigid": "DF3903E5",
      "productid": "Philips-LTA001-2-A19CTv3"
    },
    "_id": 4
  }
}
```

### PR DESCRIPTION
**Pull request by VonOx**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [X] If your changes affects code, did your write the tests?
- [X] Are tests passing? (`npm test` on both front/server)
- [X] Is the linter passing? (`npm run eslint` on both front/server)
- [X] Did you run prettier? (`npm run prettier` on both front/server)

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Adding devices to philips hue service

* Fix #891 - LWV001
* Fix #889 - LTG002
* Fix #888 - LCT012
* Fix #912 - LTA001

### CODE REVIEW

**Comment by VonOx** [comment]
@Pierre-Gilles I'm sorry but i don't know why codecov is not working on my PR

**Comment by atrovato** [comment]
If you "follow" your own Gladys git repo on circleci, codecov fails to sync with master repo.

**Comment by VonOx** [comment]
What does that mean? I need to configure something?

**Comment by atrovato** [comment]
On my side, I follow / unfollow according to my needs... there is a point to investiguate here...
No solution for now.

**Comment by VonOx** [comment]
OK , https://codecov.io/gh/VonOx/Gladys/pulls nothing in PR , but ok on commits https://codecov.io/gh/VonOx/Gladys/commits

**Comment by VonOx** [comment]
@atrovato I unfollow my own repo on circle for now. ( only need for ci testing )

https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

**Comment by Pierre-Gilles** [comment]
Thanks for your PR !

**Pull request merged**
