### PR TITLE
Allows localizing all selects by passing a translation key as label

### PR DESCRIPTION
**Pull request by rob-mccann**
### Pull Request check-list

- [x] If your changes affects code, did your write the tests?
  - coverage in frontend is limited; might propose [Preact testing library](https://testing-library.com/docs/preact-testing-library/example#test)
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [x] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

### Description of change

Follow on from #1126 with a more general solution. This new LocalizedSelect accepts options with a translation key as the label. The component will then look up the translated string and substitute the key for the string when calling react-select.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
> coverage in frontend is limited; might propose Preact testing library

@rob-mccann for the tests we are currently setting up Cypress on the whole frontend. See @atrovato PR here: https://github.com/GladysAssistant/Gladys/pull/1086

**Review by Pierre-Gilles — APPROVED** [review]
Thanks for your PR! Looks good to me

**Comment by Pierre-Gilles** [comment]
@all-contributors please add @rob-mccann for code

**Comment by rob-mccann** [comment]
@Pierre-Gilles awesome news on Cypress, I've actually used the two libraries together to cover different aspects of testing pyramid previously - where do you usually like to have these conversations
Thanks for the add to contributors too! Hoping to submit a few more requests.

**Comment by Pierre-Gilles** [comment]
I had feedbacks on the forum that this PR is breaking the Zigbee2mqtt discover screen ^^ I'll revert this PR first, and we can open it again after checking what's wrong :)

**Comment by rob-mccann** [comment]
I've identified the issue here (the intl context object isn't a stable API to call - going to move to withText or useText APIs). Will PR a fix before we can revert the revert. Bring on Cypress  - will give the MR a 👀

**Comment by Pierre-Gilles** [comment]
Yes, that's definitely something that would have been catched by Cypress, I'm looking forward to have this in Gladys :)

**Pull request merged**
