### PR TITLE
Upgrade to node 14

### PR DESCRIPTION
**Pull request by Pierre-Gilles**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Review by VonOx — DISMISSED** [review]
Seems ok and CI run is good

**Comment by atrovato** [comment]
@Pierre-Gilles did you start the server? I get many troubles:
```
2021-02-22T21:45:10+0100 <error> index.js:15 (process.<anonymous>) Error: The module '/home/alex/Gladys/server/services/bluetooth/node_modules/usb/build/Release/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

2021-02-22T21:45:07+0100 <debug> service.load.js:46 () Error: The module '/home/alex/Gladys/server/services/usb/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

2021-02-22T21:45:07+0100 <debug> service.load.js:46 () Error: The module '/home/alex/Gladys/server/services/zwave/node_modules/openzwave-shared/build/Release/openzwave_shared.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 83. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I, of course, deleted node_modules folder and re-install all from scratch, with node v14.15.5

Do I miss something?

(+ don't your package-lock.json get modified?)

**Comment by VonOx** [comment]
You think package lock need to be generated with node 14?

**Comment by atrovato** [comment]
Not sure about package-lock file, changes might not be linked to node upgrade (maybe due to my windows / wsl env).

**Comment by VonOx** [comment]
Same here under linux.

Solved by cleaning npm cache before 
`npm cache clean --force`

------------------
@atrovato 
EDIT: On WSL2 `npm rebuild` AND/OR `npm cache clean --force` not working

Need to update npm before `npm install npm@latest -g`

image

**Comment by atrovato** [comment]
I use nvm to able to switch node version easily. I will try on a new git clone.

**Comment by atrovato** [comment]
With `npm install npm@latest -g`, I get npm v7.5.6, but 6.x s required.
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '14.x', npm: '6.x' },
npm WARN EBADENGINE   current: { node: 'v14.15.5', npm: '7.5.6' }
npm WARN EBADENGINE }
```

**Comment by atrovato** [comment]
Switched to linux, `npm cache clean --force` don't do the job.
But if it's fine for you, the app well starts and not compatibility issue on startup, it will be fine for me :)

**Comment by Pierre-Gilles** [comment]
@atrovato You need to clear all node_modules folder in the server, not just the root node_modules. There should be a node_module in each services :) 

Maybe we did a script to clean them all

**Comment by VonOx** [comment]
Some additional infos related to services lock files, all modified after install.

```
M       server/services/bluetooth/package-lock.json
M       server/services/caldav/package-lock.json
M       server/services/ewelink/package-lock.json
M       server/services/example/package-lock.json
M       server/services/mqtt/package-lock.json
M       server/services/openweather/package-lock.json
M       server/services/philips-hue/package-lock.json
M       server/services/rtsp-camera/package-lock.json
M       server/services/tasmota/package-lock.json
M       server/services/telegram/package-lock.json
M       server/services/tp-link/package-lock.json
M       server/services/usb/package-lock.json
M       server/services/xiaomi/package-lock.json
M       server/services/xiaomi/package.json
M       server/services/zwave/package-lock.json
```

**Comment by VonOx** [comment]
I'm using rimraf to do a recursive cleanup

`npx rimraf ./**/node_modules`

**Comment by atrovato** [comment]
Right, I didn't remove node_modules in services. Well started now :)
Can you add the clean script here? Or in another PR?

**Comment by Pierre-Gilles** [comment]
@atrovato j'ai ajouté `npm run clean-node-modules`  :)

**Review by atrovato — APPROVED** [review]
Ok, thx :)

**Comment by atrovato** [comment]
Au fait, c'est bon pour moi :)

**Pull request merged**
