### PR TITLE
Create CODEOWNERS file

### PR DESCRIPTION
**Pull request by VonOx**
Adding CODEOWNERS

First proposal

Related doc => https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Very nice! I'm ok with that :) Could we merge to try it or is there anything more to do ?

**Comment by VonOx** [comment]
> Very nice! I'm ok with that :) Could we merge to try it or is there anything more to do ?

Yes you can merge

**Comment by Pierre-Gilles** [comment]
Screenshot 2021-01-29 at 09 57 09


Just read that, I don't think it'll work for now...

**Comment by VonOx** [comment]
> Just read that, I don't think it'll work for now...

For merging ? But for PR approval I think this is OK

Nevermind , you can just take the file or freeze this PR for later

**Comment by VonOx** [comment]
Another reading => https://github.blog/2017-07-06-introducing-code-owners/

I'm not sure why write permissions is needed for review assignment.

**Pull request closed without merging**
