### PR TITLE
Scenes binary sensor labels

### PR DESCRIPTION
**Pull request by atrovato**
Please look at old PR for history #1462 
I fixed small screen view.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
@atrovato 

Better, but there is still an alignment problem with the buttons! 

Before:

Screenshot 2022-08-04 at 11 15 37

After:
Screenshot 2022-08-04 at 11 14 44

**Comment by atrovato** [comment]
I think I will take more time on this, the page is not fully responsive.

image

Maybe we need to have one line per form part in mobile view...
I will play with and keep you in touch.

**Comment by atrovato** [comment]
And now? @Pierre-Gilles 

image

**Comment by Pierre-Gilles** [comment]
What about putting the arrow vertically when in mobile ? 

More classic pattern: 

Screenshot 2022-11-25 at 15 48 39

**Comment by atrovato** [comment]
@Pierre-Gilles done ;)

image

**Review by Pierre-Gilles — APPROVED** [review]
So much better now !! Love this design on mobile 😄

**Pull request merged**
