### PR TITLE
Improve english localization-closes #674

### LINKED ISSUE #674: Improve English translation/localization
I recently installed Gladys and went through a new user flow (super great/cool project by the way!) and noticed that the English localization could be cleaned up a little bit in terms of spelling/grammar/word choice.

As a native English speaker, I'd be more than happy to go through this (in fact I already started) and submit a PR with the improved copy.

### PR DESCRIPTION
**Pull request by Scott-Fischer**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/gladys-4-docs) and the [website](https://documentation.gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Simple improvements to english translations as discussed in issue #674

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Thanks for your PR 🙌 

Is it ready for review/merge?

**Comment by Scott-Fischer** [comment]
Yes it is!

**Comment by Pierre-Gilles** [comment]
Many thanks for this PR, just merged it 🙏

**Comment by Pierre-Gilles** [comment]
@all-contributors please add @Scott-Fischer for translation

**Pull request merged**
