### PR TITLE
Script to test single service

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~If your changes affects code, did your write the tests?~~
- ~~Are tests passing? (`npm test` on both front/server)~~
- ~~Is the linter passing? (`npm run eslint` on both front/server)~~
- ~~Did you run prettier? (`npm run prettier` on both front/server)~~
- ~~If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/gladys-4-docs) and the [website](https://documentation.gladysassistant.com).~~
- ~~Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Add script to test single service.
Usage `SERVICE=zwave npm run test-service`

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Nice! Could it be possible to have a parameters instead of a env variable? Like :

```
npm run test-service zwave
```

?

**Comment by atrovato** [comment]
I searched for, but didn't find anything for npm scripts using command args.
I'll search more this evening.

**Comment by atrovato** [comment]
I can't find any other simple solution.

**Comment by hotfix31** [comment]
I think it's possible:
https://docs.npmjs.com/cli/run-script#description

> As of npm@2.0.0, you can use custom arguments when executing scripts. The special option -- is used by getopt to delimit the end of the options. npm will pass all the arguments after the -- directly to your script:
```npm run test -- --grep="pattern"```
The arguments will only be passed to the script specified after npm run and not to any pre or post script.

**Comment by atrovato** [comment]
I may mis something, but I can't make it work.
It will be easier to create a JS file to handle param and execute service tests.

**Comment by atrovato** [comment]
Updated to `npm run test-service --service=tasmota`

**Comment by Pierre-Gilles** [comment]
Merci pour cette PR ! :) Je regarde la semaine prochaine lors de mes jours Gladys.

**Comment by Pierre-Gilles** [comment]
Thanks for your PR ! 

I updated the doc with the script: 

https://gladysassistant.com/fr/docs/api/setup-development-environnement#lancer-les-tests-dun-seul-service

**Pull request merged**
