### PR TITLE
Sync deleted events

### PR DESCRIPTION
**Pull request by bertrandda**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Deleted events did not sync anymore since this PR https://github.com/GladysAssistant/Gladys/pull/1471

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Indeed, I saw the bug on my instance :D Did you test the fix on your side?

**Comment by bertrandda** [comment]
> Indeed, I saw the bug on my instance :D Did you test the fix on your side?

Yes with a Nextcloud CalDAV account

**Review by Pierre-Gilles — COMMENTED** [review]
I'm not sure this is the way to try this PR, but I created an event in my Google Calendar, then synced: the event is displayed in the calendar.

Then, I delete the event from Google.

I sync again: the event is still there! 

Also, not sure it's related, but when I synced the first time I got this error:

```
2022-06-10T09:41:59+0200 <error> calendar.syncUserCalendars.js:72 (Promise.map.concurrency) Error: Bad status: 403
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/dav-request/dav.js:3424:27)
    at exports.XMLHttpRequest.dispatchEvent (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Then, it worked again at the second sync

**Comment by bertrandda** [comment]
I found an issue with Google but not 403 error. The last commit fix same kind of problem that there was [here](https://github.com/GladysAssistant/Gladys/pull/1471/files#diff-5bef161e258bc3303ba6019ecf6297ed05b00ef92460f588f29037687aa298ddR118)
Can you tell me if that resolve deletion on your side? If not, can we investigate your 403?

**Comment by Pierre-Gilles** [comment]
@bertrandda Thanks ! I have no idea how to reproduce for the 403

**Review by Pierre-Gilles — COMMENTED** [review]
I tried it but it doesn't work! 

What I did (on Google Calendar):

- I create an event in Google calendar
- I sync the Caldav calendar in Gladys (the event appears in the UI)
- I delete the event in Google calendar
- The event is still displayed

Am I doing something wrong?

**Comment by bertrandda** [comment]
> I tried it but it doesn't work!
> 
> What I did (on Google Calendar):
> 
>     * I create an event in Google calendar
> 
>     * I sync the Caldav calendar in Gladys (the event appears in the UI)
> 
>     * I delete the event in Google calendar
> 
>     * The event is still displayed
> 
> 
> Am I doing something wrong?

Did you sync again after delete event on Google Calendar?

**Comment by Pierre-Gilles** [comment]
@bertrandda Yes several times

**Comment by bertrandda** [comment]
> @bertrandda Yes several times

Do you have any log?
I just tried it with my own Google account it works as expected.
Does your calendar have special char or do you test with special event (recurent, full day...)?
When you have time, could we investigate?

**Comment by Pierre-Gilles** [comment]
@bertrandda Just tested again, on the first sync I got a 403: 

```
2022-09-08T11:34:10+0200 <error> calendar.syncUserCalendars.js:72 (Promise.map.concurrency) Error: Bad status: 403
    at exports.XMLHttpRequest.request.onreadystatechange (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/dav-request/dav.js:3424:27)
    at exports.XMLHttpRequest.dispatchEvent (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/pierregilles/code/gladys/server/services/caldav/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Then when I sync again it works (might be a token expired error?)

I tried again the scenario described on top, and this time it worked! So I guess it's good for me this time :D 

For the 403, any idea how we could solve this?

**Review by Pierre-Gilles — APPROVED** [review]
As the scenario worked for me this time, it's good for me on this one!

It could be nice to investigate the 403 though, but it's fine in another PR :)

**Pull request merged**
