### PR TITLE
Dashbaord CO with colored badge

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~[ ] If your changes affects code, did your write the tests?~~
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- ~~[ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.~~
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

CO sensor as colored badge.
https://community.gladysassistant.com/t/type-qualite-de-lair-natif-avec-couleurs-en-fonction-de-la-valeur/7014

A little refacto to allow to enlarge easily and clearly the way to display sensor values.

image

### CODE REVIEW

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
It seems the "door opening sensor" are not working when in position 1 : 

Screenshot 2022-03-18 at 08 49 12

Otherwise, very nice PR ! It works fine for the Co2 part :)

**Comment by atrovato** [comment]
You're right, I wrote `shield-on` instead of `shiled` as icon class.

**Review by Pierre-Gilles — APPROVED** [review]
Looks good to me! Thanks for your PR 🙏

**Comment by Pierre-Gilles** [comment]
@atrovato Just one question, where did you find your values for the Co2 limits ?

I find way different values online: 

Screenshot 2022-03-22 at 09 26 34

**Comment by Pierre-Gilles** [comment]
Indice-PPM-1-1024x538

**Pull request merged**
