### PR TITLE
Adding links to Github and Gladys Website

### PR DESCRIPTION
**Pull request by VonOx**
They are in the header beside the user menu

Screenshot

### CODE REVIEW

**Comment by VonOx** [comment]
Maybe translation is not necessary ?
Or if i understand the mechanics ==>  "View on github":"Voir sur Github" is good enough for fr and en ?

**Comment by Pierre-Gilles** [comment]
I don't know if putting github and website links in the navbar is a good ideas, it's maybe too visible !

I would prefer like in the footer or something like that.

For the translation that's perfect, you have understood :) The way you've done it is the best practice. 

I know sometimes I just write  "English-text":"french-text" and nothing in the en file, but that's not a good practice, I need to change that

**Comment by VonOx** [comment]
Yes, i agree
The problem, this version of admin Lte have no footer / Need update or customize.

**Comment by Pierre-Gilles** [comment]
Ok I think updating the theme can be the best solution, but it will take some time. I'll make some tests at home!

**Comment by VonOx** [comment]
I have started the update yersteday.

The blue light skin have white sidebar

**Comment by VonOx** [comment]
Can you close this PR ?

**Pull request closed without merging**
