### PR TITLE
Push docker images to GHCR

### PR DESCRIPTION
**Pull request by VonOx**
Updating CI to push image to Github Container Registry
Good bandwidth and no request limitation.

For those using watchtower with a lot of container its a good choice.

Tested here => https://github.com/VonOx/gh-test-ci/pkgs/container/gladys

### CODE REVIEW

**Comment by atrovato** [comment]
Does it mean that we have to declare a `GITHUB_TOKEN` or Github knows itself?

It looks really clean ;)

**Comment by VonOx** [comment]
Token is available in CI, nothing to do.

**Comment by Pierre-Gilles** [comment]
Very nice, good idea! Do you confirm that we still push to DockerHub, it's just a second destination?

**Comment by VonOx** [comment]
Yes dockerhub stuff still here, just another destination.

**Review by Pierre-Gilles — APPROVED** [review]

**Pull request merged**
