### PR TITLE
Zigbee2mqtt devices

### LINKED ISSUE #1118: zigbee2mqtt:5 zigbee2mqtt supported devices cannot add to gladys
my devices TT001ZAV20 has support in zibgee2mqtt ,follow `https://www.zigbee2mqtt.io/devices/TT001ZAV20.html#tuya-tt001zav20`

but,i can't add in gladys, ,and it has recognized,in zigbee2mqtt from 8080 port web

image
image
image

```
{
  "name": "0x000d6ffffe6eca47",
  "external_id": "zigbee2mqtt:0x000d6ffffe6eca47",
  "model": "TT001ZAV20",
  "features": [
    {
      "category": "battery",
      "type": "integer",
      "unit": "percent",
      "name": "Battery",
      "read_only": true,
      "has_feedback": false,
      "min": 0,
      "max": 100,
      "zigbeeField": "battery",
      "external_id": "zigbee2mqtt:0x000d6ffffe6eca47:battery:integer:battery",
      "selector": "zigbee2mqtt:0x000d6ffffe6eca47:battery:integer:battery"
    }
  ],
  "should_poll": false,
  "service_id": "cd5e56de-fd54-446d-a5a7-2539273349d9",
  "supported": false
}
```

also many of zigbee2mqtt supported device cannot 

`https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html`
```
{
  "name": "0x04cf8cdf3c7d5ce3",
  "external_id": "zigbee2mqtt:0x04cf8cdf3c7d5ce3",
  "model": "WXCJKG13LM",
  "features": [
    {
      "category": "battery",
      "type": "integer",
      "unit": "percent",
      "name": "Battery",
      "read_only": true,
      "has_feedback": false,
      "min": 0,
      "max": 100,
      "zigbeeField": "battery",
      "external_id": "zigbee2mqtt:0x04cf8cdf3c7d5ce3:battery:integer:battery",
      "selector": "zigbee2mqtt:0x04cf8cdf3c7d5ce3:battery:integer:battery"
    }
  ],
  "should_poll": false,
  "service_id": "cd5e56de-fd54-446d-a5a7-2539273349d9",
  "supported": false
}
```

some images: my 5 devices can find in zigbee2mqtt supported,but only one device can add to gladys 
image

image
image
image

### `my five devices:`

[RH3040](https://www.zigbee2mqtt.io/devices/RH3040.html)    ☑️ only this one can add to gladys

[TT001ZAV20](https://www.zigbee2mqtt.io/devices/TT001ZAV20.html#tuya-tt001zav20)

[SNTZ007](https://www.zigbee2mqtt.io/devices/SNTZ007.html)

[WXCJKG13LM](https://www.zigbee2mqtt.io/devices/WXCJKG13LM.html)

[SN10ZW](https://www.zigbee2mqtt.io/devices/SN10ZW.html)

image

### PR DESCRIPTION
**Pull request by VonOx**
Just to handle some missing devices

* Fix #1118 for sensors devices ( 3 / 4 )

### CODE REVIEW

**Review by LM1LC3N7 — DISMISSED** [review]
Can we push this to the dev docker image, for testing?

**Review by atrovato — DISMISSED** [review]

**Review by atrovato — APPROVED** [review]

**Review by Pierre-Gilles — APPROVED** [review]
Nice! :)

**Comment by Pierre-Gilles** [comment]
Dev build in progress: https://github.com/GladysAssistant/Gladys/actions/runs/722403774

**Comment by bulolo** [comment]
where can i get this dev docker for test？ Is there a raspi image for test

**Comment by LM1LC3N7** [comment]
> 
> 
> where can i get this dev docker for test？ Is there a raspi image for test

Directly from the docker hub: https://hub.docker.com/r/gladysassistant/gladys/tags?page=1&ordering=last_updated

So, this should work:

```bash
docker run -d \
--log-opt max-size=10m \
--restart=always \
--privileged \
--network=host \
--name gladys-dev \
-e NODE_ENV=dev \
-e SERVER_PORT=8080 \
-e TZ=Europe/Paris \
-e SQLITE_FILE_PATH=/var/lib/gladysassistant/gladys-dev.db \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /var/lib/gladysassistant:/var/lib/gladysassistant \
-v /dev:/dev \
-v /run/udev:/run/udev:ro \
gladysassistant/gladys:dev
```

Gladys will use another database file `gladys-dev` and run on port 8080.

**Pull request merged**
