### PR TITLE
Add features energy on Tasmota devices, fixes features on server and fixes i18n units energies front

### PR DESCRIPTION
**Pull request by Terdious**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

See the exchanges on Gladys community : https://community.gladysassistant.com/t/plusieurs-erreurs-manques-pour-tasmota-pow-r2/7306
- Fixed an error on the intensity feature which was translated into energy.
- Fixed the voltage which was /1000 and transformed the voltage from Volt to mVolt for no apparent reason (if on other devices the voltage is retransmitted in milliVolt then the user will have to select the correct unit in the edit menu of the device)
- Fixed energy feature category and type to `ENERGY_SENSOR` rather than `SWITCH` to get the correct units in the edit devices/features menu
- Addition of the following energy data (in particular for the Sonoff POW-Rx model):
  - Apparent power consumption,
  - Reactive power consumption,
  - Total energy,
  - Today's energy.
- Fixed the reactive Volt Ampere unit on the front side which in the i18n files was lowercase (var instead of VAr)
- Fixed the Watt and kiloWatt units on the front side which were not mentioned in the `fr.json` file ("Watt" instead of "Watt (W)" and "KiloWatt" instead of "KiloWatt (kW)") but was good in `en.json` file

### CODE REVIEW

**Comment by Terdious** [comment]
It looks like this after modification :
image
image

**Review by VonOx — COMMENTED** [review]
Looks fine

**Review by VonOx — DISMISSED** [review]

**Review by atrovato — DISMISSED** [review]
Code looks great, but this may have impacts on existing instances.
Maybe you can automatically update changed feature in database (switch to energy_sensor), but this may have side effects on history.

**Comment by Terdious** [comment]
> Code looks great, but this may have impacts on existing instances. Maybe you can automatically update changed feature in database (switch to energy_sensor), but this may have side effects on history.

Hey @atrovato !! thank you very much for your review.
Yes indeed I thought about it. Indeed going through a DB migration file is one of the solutions. But I was thinking that the user should perhaps be master of the latter. Wouldn't it be possible to communicate when switching to the new version to ask users, if they wish, to refresh the discovery page of the Tasmota integration and update their affected devices?
For my part, I tested starting from a device before change directly on this PR, and nothing "broken", the device still works on the dashboard because we take into account the selector, and the recording of states did not change selector or external_id for current and voltage.

I can try a test campaign on gladys community if necessary, but not sure that someone else has one because no feedback had been made on the problem of intensity ^^
Video update with console logs :
Tasmota POWR2

Before : 
Avant changement dashboard
Avant changement feature

After :
Après changement dashboard
Après changement feature

**Comment by Terdious** [comment]
@Pierre-Gilles

**Comment by atrovato** [comment]
@Terdious 
Please try something like this for DB update:

`server/migrations/20220716071308-update-tasmota-energy-features.js`

```javascript
const Promise = require('bluebird');
const sequelize = require('sequelize');
const db = require('../models');

module.exports = {
  up: async () => {
    // Get Tasmota service
    const service = await db.Service.findOne({
      attributes: ['id'],
      where: {
        name: 'tasmota',
      },
    });

    // Load impacted features
    const features = await db.DeviceFeature.findAll({
      where: {
        category: 'switch',
        type: ['energy', 'power', 'voltage'],
      },
      include: [
        {
          model: db.Device,
          as: 'device',
          where: {
            service_id: service.id,
          },
        },
      ],
    });

    await Promise.map(features, async (feature) => {
      const { id, type, name, last_value: value } = feature;

      // Modify energy current
      if (type === 'energy') {
        const currentFields = {
          category: 'energy-sensor',
          type: 'current',
        };

        if (name === 'Energy') {
          currentFields.name = 'Intensity';
        }

        await feature.update(currentFields);
      }

      // Modify energy power
      if (type === 'power') {
        const currentFields = {
          category: 'energy-sensor',
          unit: 'watt',
        };

        await feature.update(currentFields);
      }

      // Modify energy voltage
      if (type === 'voltage') {
        const currentFields = {
          category: 'energy-sensor',
          unit: 'watt',
          last_value: value * 1000,
        };

        await feature.update(currentFields);
        // Update feature states
        await db.DeviceFeatureState.update(
          {
            value: sequelize.literal('value * 1000'),
          },
          {
            where: {
              device_feature_id: id,
            },
          },
        );
        // Update feature aggregate
        await db.DeviceFeatureStateAggregate.update(
          {
            value: sequelize.literal('value * 1000'),
          },
          {
            where: {
              device_feature_id: id,
            },
          },
        );
      }
    });
  },
  down: async () => {},
};
```
@Pierre-Gilles any opinion?

It looks like the community is waiting for this changes.

**Comment by Pierre-Gilles** [comment]
@atrovato Looks fine but the Promise.map without concurrency is too aggressive

Use Promise.mapSeries or add a small concurrency :)

**Comment by Pierre-Gilles** [comment]
@Terdious FYI, I merged this PR first : https://github.com/GladysAssistant/Gladys/pull/1571

It seems there are now some conflicts that breaks the test, could you have a look please ? 🙂 

Thanks you for this PR !

**Comment by VonOx** [comment]
@Pierre-Gilles can you review again, I have fixed the test.

**Review by VonOx — DISMISSED** [review]
@Pierre-Gilles I've fixed the test and added db migration file. Can you review again ?

**Comment by gboulvin** [comment]
Does this commit just needs more tests to be merged ?

**Comment by atrovato** [comment]
The pull request has been automically closed due to a lack of activity.
So I just re-open it.

**Comment by Terdious** [comment]
I just saw that there were requests and updates. It might be time for me to get back to it. I updated the branch, no conflict!! Good sign.

@atrovato, @VonOx, @Pierre-Gilles ?
Well, on the other hand, I still have a serious problem with the representation of feature names on Dashboard and curves. Here as we have more "Energy" and "Power", everything is fine! But for Intensity and Tension...it sucks. The only indication we have is the unit...
image

Couldn't we make a condition:
`If name of the modified feature => we take this one. If not modified, we take the original name of the dev`

Thank you in advance.

@Pierre-Gilles  I think you can review !!

**Review by Pierre-Gilles — APPROVED** [review]
Good for me on the code part! 

How tested was this in real life? Was the migration tested?

**Pull request merged**
