### PR TITLE
Device feature display name

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~[ ] If your changes affects code, did your write the tests?~~
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Display feature name in case of multiple identical category/type features in a device.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Interesting feedback: https://community.gladysassistant.com/t/besoin-de-vous-un-nouvel-affichage-dashboard-des-noms-dappareils-pour-les-appareils-complexe/7559/22?u=pierre-gilles

**Comment by atrovato** [comment]
Changed according to proposal @Pierre-Gilles (one new commit if you want to cherry-pick).

**Comment by Pierre-Gilles** [comment]
@atrovato I know why it doesn't work on the chart view, the "device" object is just the device name.

I added a log here:

Screenshot 2022-10-10 at 12 28 49

And saw that: 

Screenshot 2022-10-10 at 12 28 53

But it's normal, we don't return the full device object in this route (to keep it as light as possible)

I'm not sure we want to add more data to this route, maybe the solution here is just to display the feature name in any case because in this feature we don't target devices like Philips Hue that don't save chart data

**Comment by atrovato** [comment]
So I add a new commit to keep only feature name on charts (branch rebased from master).

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Feedbacks: https://community.gladysassistant.com/t/besoin-de-vous-un-nouvel-affichage-dashboard-des-noms-dappareils-pour-les-appareils-complexe/7559/36?u=pierre-gilles

**Comment by atrovato** [comment]
@Pierre-Gilles 2 new commits:

 - 04bfdb01499c97a79e6f771357076f9f546240b6: vonox suggestion to use only type and not category to check multiple features
 - 8876782b53972362b4926ccc7d72cdb348b41d4a: display feature name in charts

I rebased the branch with master.

🤞

**Review by Pierre-Gilles — APPROVED** [review]
Thanks for this PR! Looks good to me :)

**Pull request merged**
