### PR TITLE
Z2m dongle configuration

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

According to https://community.gladysassistant.com/t/zigbee2mqtt-services-demarres-mais-croix-rouge-pour-le-lien/7955/20?u=alextrovato

Add the possibility to select the Zigbee USB dongle used with Gladys.
It add the "adapter" config to z2m configuration file.
It is based on dongle name (not adapter key). It allows to update the mapping with z2m configuration easily, and avoid database manipulation to re-adapt it.
Due to this, the evolution also handle non managed dongle, which resets the adapter value in z2m config.

⚠️ The dongle list is hardcoded, and not dynamic, based on https://www.zigbee2mqtt.io/guide/adapters/.

I also removed the "action.js" file on the modified part and replaced the shell script with javascript functions.

image

Test image: `atrovato/gladys:zigbee2mqtt`

### CODE REVIEW

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Very nice PR! Thanks for working on it 🙏

A few feedbacks:

There are no placeholder on the select box: 

Screenshot 2023-05-05 at 10 07 20

The button "Rafraichir la liste des appareils USB" is not working anymore

Otherwise, it works fine to me!

**Comment by atrovato** [comment]
Thank you for your feedbacks.
Both remarks are taken into account, and pushed (branch rebased on master):

z2m-dongle-fixes

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Very nice! 

Way better :) 

Just a question, when I change the USB dongle model, Zigbee2mqtt doesn't seem to reload. Is it the expected behavior? Is Zigbee2mqtt automatically loading the configuration.yaml when it changes?

Other feedback, not related to this PR, but since you're improving the UX it might be great to change it too:

The mobile screen is not nice : 

Screenshot 2023-05-05 at 17 45 35

I think just adding this to the text (`d-none d-md-inline-block`) : 

```
 <button class="btn btn-info" onClick={props.getUsbPorts}>
      <i class="fe fe-rotate-cw" />{' '}
      <span class="d-none d-md-inline-block">
        <Text id="integration.zigbee2mqtt.settings.refreshButton" />
      </span>
    </button>
```

Make it better: 

Screenshot 2023-05-05 at 17 53 56

What do you think ?

**Comment by atrovato** [comment]
> when I change the USB dongle model, Zigbee2mqtt doesn't seem to reload. Is it the expected behavior? Is Zigbee2mqtt automatically loading the configuration.yaml when it changes?

You need to click on Save button to force docker containers and their configuration to apply selected changes (calling `/api/v1/service/zigbee2mqtt/setup` endpoint).

> The mobile screen is not nice

You're right, I do change it (and rebase from master).
I also add `ml-2` class to keep space between icon and text.

**Comment by Pierre-Gilles** [comment]
@atrovato 

> You need to click on Save button to force docker containers and their configuration to apply selected changes (calling /api/v1/service/zigbee2mqtt/setup endpoint).

Are you sure about that ? I was clicking on save and Zigbee2mqtt didn't seem to reload

**Comment by atrovato** [comment]
Clicking on save button, I see this in Gladys logs:

```
configureContainer.js:18 (Zigbee2mqttManager.configureContainer) Z2M Docker container is being configured...
configureContainer.js:28 (Zigbee2mqttManager.configureContainer) Z2M configuration file already exists.
installZ2mContainer.js:72 (Zigbee2mqttManager.installZ2mContainer) Zigbee2mqtt container successfully started
```

It says:
1. configuration file written
2. z2m reload/restarted

And in z2m container logs, I see it well restarts:
```
Zigbee2MQTT:error 2023-05-06 06:58:39: Exiting...
Zigbee2MQTT:error 2023-05-06 06:58:39: undefined
Using '/app/data' as data directory
Using '/app/data' as data directory
Zigbee2MQTT:info  2023-05-06 06:58:46: Logging to console and directory: '/app/data/log/2023-05-06.06-58-46' filename: log.txt
Zigbee2MQTT:info  2023-05-06 06:58:46: Starting Zigbee2MQTT version 1.30.4 (commit #b2dd21e)
Zigbee2MQTT:info  2023-05-06 06:58:46: Starting zigbee-herdsman (0.14.111)
```

And in confuration.yaml, I can see
```yaml
serial:
  port: /dev/ttyACM0
  adapter: deconz # or not according to the dongle model
```

@Pierre-Gilles are you sure you force to pull the latest test image?

**Comment by Pierre-Gilles** [comment]
@atrovato Tested again locally (docker pull, docker stop, docker rm, docker run), and it doesn't restart Zigbee2mqtt 

**My test:**

- Set the USB port
- Set the Zigbee dongle model
- Click on "save"
- Zigbee2mqtt is ok
- Change the Zigbee dongle model only
- Click on "save"
- No restart

Is it a normal behavior?

**Comment by Pierre-Gilles** [comment]
@atrovato Other feedback:

Every-time I save, I see in the logs: 

```
2023-05-08T08:41:54+0200 <info> connect.js:18 (Zigbee2mqttManager.connect) Connecting Gladys to mqtt://localhost:1884 MQTT broker...
2023-05-08T08:41:54+0200 <info> connect.js:28 (MqttClient.<anonymous>) Connected to MQTT container mqtt://localhost:1884
2023-05-08T08:41:54+0200 <info> subscribe.js:12 (Zigbee2mqttManager.subscribe) Subscribing to MQTT topic zigbee2mqtt/#
```

Does it means it creates a new listener every time I click on save ? Does Gladys receive Z2M messages multiple times?

**Comment by atrovato** [comment]
Every time you save configuration, only if USB Port is defined, it calls:

* `installMQTTcontainer.js`
  1. looks for existing `gladys-z2m-mqtt` named container
  2. if not exists
     * create it
     * restart it
     * setup password
     * restart container to take password config into account
  3. it container exists
     * check for container state
     * if not running, starts it 
* `installZ2MContainer.js`
  1. looks for existing `gladys-z2m-zigbee2mqtt` named container
  2. if not exists
     * restore backup
     * create it
  3. write z2m config if necessary
  4. check for container state
  5. if not running, starts it
* both containers are setup -> `connect.js`
  1. only if MQTT is "running"
  2. create a client on it and connect to MQTT
     * "Connecting Gladys to mqtt://localhost:1884 MQTT broker..."
     * "Connected to MQTT container mqtt://localhost:1884"
  3. **BUT I can't see any disconnect before creating a new client!**


But in any case, the `setup` method called by the "USB configuration" page will call this flow, so will enter in `write z2m config if necessary` if USB port is defined.

Don't you see any of this following logs?

```
Z2M Docker container is being configured...
Z2M configuration file already exists.
```

Those lines means you enter in the "write configuration.yaml file" phase.

ℹ️ I will add a new log line once additional config have to be written.

---

➕ For more, if the "special adapter setup" is not changed, configuration file is not written.
To test it, you'll need to check https://www.zigbee2mqtt.io/guide/adapters/ page, or `server/services/zigbee2mqtt/adapters/index.js` file and change for different config key adapters.

By exemple:
 - `deconz`
    - ConBee
    - RaspBee
 - `ezsp`
    - Elelabs ELU013 and Popp ZB-STICK
    - ITead Sonoff Zigbee 3.0 USB Dongle Plus V2 model "ZBDongle-E
 - `<none>`
    - Electrolama zig-a-zig-ah! (zzh!)
    - Texas Instruments CC2530

If you select `ConBee` first, then save, it will write `deconz` value in config file.
If you select `RaspBee` second, then save, **it will not write config again**, as `deconz` value is already in config file.
If you select `zzh` third, then save, it will remove `adapter` value from config file (as `<none>` is expected).

But in any cases, MQTT/z2m containers are checked, config written if necessary (values changed only).

Let me know if it is not clear enough, we can have a call.

---

ℹ️ I do add the new log line, and rebase from master.
👍 I also add the "disconnect" phase once we try to connect again to MQTT

A new image is building, wait for 1h to get it!

**Comment by Pierre-Gilles** [comment]
@atrovato Ok with the logic, but I don't see the case where "The configuration file was updated -> restart Zigbee2mqtt" ?

Does Zigbee2mqtt needs to restart to take into account changes in the configuration.yaml ? 

I just tried locally again (with new image), and I see that in the logs: 

```
23-05-08T11:52:10+0200 <info> checkForContainerUpdates.js:14 (Zigbee2mqttManager.checkForContainerUpdates) Checking for current installed versions and required updates...
2023-05-08T11:52:10+0200 <info> installMqttContainer.js:120 (Zigbee2mqttManager.installMqttContainer) MQTT broker container successfully started
2023-05-08T11:52:10+0200 <info> configureContainer.js:18 (Zigbee2mqttManager.configureContainer) Z2M Docker container is being configured...
2023-05-08T11:52:10+0200 <info> configureContainer.js:28 (Zigbee2mqttManager.configureContainer) Z2M configuration file already exists.
2023-05-08T11:52:10+0200 <info> configureContainer.js:63 (Zigbee2mqttManager.configureContainer) Writting MQTT and USB adapter information to Z2M configuration...
2023-05-08T11:52:10+0200 <info> installZ2mContainer.js:72 (Zigbee2mqttManager.installZ2mContainer) Zigbee2mqtt container successfully started
2023-05-08T11:52:10+0200 <info> connect.js:17 (Zigbee2mqttManager.connect) Disconnecting existing MQTT client...
2023-05-08T11:52:10+0200 <info> connect.js:25 (Zigbee2mqttManager.connect) Connecting Gladys to mqtt://localhost:1884 MQTT broker...
2023-05-08T11:52:10+0200 <info> connect.js:35 (MqttClient.<anonymous>) Connected to MQTT container mqtt://localhost:1884
2023-05-08T11:52:10+0200 <info> subscribe.js:12 (Zigbee2mqttManager.subscribe) Subscribing to MQTT topic zigbee2mqtt/#
```

And Zigbee2mqtt hasn't restarted: 

Screenshot 2023-05-08 at 16 54 11

Is it a normal behavior? ^^

I'm available for a call too if needed :)

**Comment by atrovato** [comment]
Ok, re-ready the code, it starts the z2m container only it's not running (kept as it was done on 1st version of the dev).
So you're right, I'm gonna change it the force the container to restart.

Thank you, you get the QA tester badge ;)

**Comment by atrovato** [comment]
```
2023-05-08T14:32:53+0200 <info> init.js:39 (Zigbee2mqttManager.init) Zigbee2mqtt USB dongle attached to /dev/ttyUSB0
2023-05-08T14:32:53+0200 <info> checkForContainerUpdates.js:14 (Zigbee2mqttManager.checkForContainerUpdates) Checking for current installed versions and required updates...
2023-05-08T14:32:53+0200 <info> installMqttContainer.js:120 (Zigbee2mqttManager.installMqttContainer) MQTT broker container successfully started
2023-05-08T14:32:53+0200 <info> configureContainer.js:18 (Zigbee2mqttManager.configureContainer) Z2M Docker container is being configured...
2023-05-08T14:32:53+0200 <info> configureContainer.js:28 (Zigbee2mqttManager.configureContainer) Z2M configuration file already exists.
2023-05-08T14:32:53+0200 <info> installZ2mContainer.js:67 (Zigbee2mqttManager.installZ2mContainer) Zigbee2mqtt container is (re)starting...
2023-05-08T14:32:59+0200 <info> installZ2mContainer.js:72 (Zigbee2mqttManager.installZ2mContainer) Zigbee2mqtt container successfully started
2023-05-08T14:32:59+0200 <info> connect.js:17 (Zigbee2mqttManager.connect) Disconnecting existing MQTT client...
2023-05-08T14:32:59+0200 <info> connect.js:25 (Zigbee2mqttManager.connect) Connecting Gladys to mqtt://localhost:1884 MQTT broker...
2023-05-08T14:32:59+0200 <info> connect.js:35 (MqttClient.<anonymous>) Connected to MQTT container mqtt://localhost:1884
2023-05-08T14:32:59+0200 <info> subscribe.js:12 (Zigbee2mqttManager.subscribe) Subscribing to MQTT topic zigbee2mqtt/#
```

It's quite better, it's been well restarted now!
The test image is up-to-date.
Thank you!!!

**Review by Pierre-Gilles — APPROVED** [review]
Tested on my side, it works fine! Thanks for the changes 🙏

**Pull request merged**
