### PR TITLE
CircleCI & Docker - Handle rate limitation and cleaned workflow variable

### LINKED ISSUE #897: Handle DockerHub rate limit in CI
https://support.circleci.com/hc/en-us/articles/360049758552-My-build-fails-to-pull-Docker-image-with-Too-Many-Requests-Rate-Limiting-by-Docker-Hub

### PR DESCRIPTION
**Pull request by VonOx**
### Description of change

* Fix #897 ( DockerHub introduce rate limit so we need docker login before any action )
* I have modified load_env.sh
  * Cleaned some useless variable
  * IMAGE_ID is now set from CircleCI variable DOCKERHUB_REPO , any dev can set his own jobs.
  * Updated QEMU to 5.1.0-5
* Fixed ARG in Dockerfile ( docker inspect must return Build Date and Version of Gladys )
* Fixed circleci config as discussed with @atrovato ( master now quoted )

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Thanks for this PR ! Did you try a build on your repo ? (it works?)

**Comment by VonOx** [comment]
> 
> 
> Thanks for this PR ! Did you try a build on your repo ? (it works?)

Not a full build in circle ( no change in circleci )
I have builded docker image in local for testing ARG and variables

I will setup an isolated repo for full build if you need

**Comment by Pierre-Gilles** [comment]
thanks a lot! :) Yes I think It's better to try on a dumb repo before trying this in prod

**Comment by VonOx** [comment]
Success Job https://app.circleci.com/pipelines/github/VonOx/GLADYS_CI/19/workflows/0cddd81b-56ac-4f99-b0c7-965963366ca8/jobs/78

**Comment by Pierre-Gilles** [comment]
Thanks for your work! :) 

This is my CircleCI configuration: 

Screenshot 2020-10-26 at 18 40 46

I have nothing to change right?

**Comment by VonOx** [comment]
Nothing, DOCKERHUB_REPO = gladysassistant/gladys :wink:

**Pull request merged**
