### PR TITLE
OAuth server capability

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If your changes modify the API (REST or Node.js), did you modify the documentation? (Documentation is based on comments in code)

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Allow OAuth2 link between Gladys and third party applications.
 - connection page
 - allow / deny page
 - common OAuth2 card to be integrated within integration pages

Server side:
 - store client session
 - follow OAuth2 workflow

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Hello! 

Good work on this one too :)

One question, why did you create another table for Oauth session? I think we can simply use the `t_session` table, which was designed exactly like OAuth 2.0 (Refresh_token + access_token, scope + expire date)

**Comment by atrovato** [comment]
Thank you.
I didn't this table, I will change this ASAP.
But I will try with a client to validate it works fine before asking to merge.

**Comment by Pierre-Gilles** [comment]
Sure :)

**Comment by Pierre-Gilles** [comment]
Why don't you use auto onsave prettier ? ( With VSCode for example)

it saves a lot of time ^^

**Comment by atrovato** [comment]
Great idea, i add `"editor.formatOnSave": true` to VSCode settings, thank you.
I this case, I was on rebase with master, not editing file.

**Comment by atrovato** [comment]
Ready to review, I will preprare a docker image with Google Actions (Google Home) integration to be able to test it.

**Comment by atrovato** [comment]
I create a docker image to test it via Google Home: atrovato/gladys:google-actions
Documentation to configure Google (english): https://github.com/GladysAssistant/v4-website/pull/54/files

Google device syncing part is not totally done (#631), but it allows to check the OAuth2 workflow.

I think we'll need to find a way to avoid "user specific configuration" for Gladys Gateway clients.

**Comment by Pierre-Gilles** [comment]
Hey @atrovato ! I answered you on the forum here: https://community.gladysassistant.com/t/integrer-gladys-dans-googlehome/5553/4

I think there is a real reflexion to have before doing this.

**Comment by atrovato** [comment]
Close it until security warning on dependency is fixed.

**Pull request closed without merging**
