### PR TITLE
Nervermind - I18 birthdate placeholder

### PR DESCRIPTION
**Pull request by Molkobain**
Fix to enhance registration form by adding a localised placeholder to the birthdate.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Thanks for the PR !

But date in English in Sails.js is "YYYY-MM-DD", not "mm/dd/yyyy" ! :D

**Comment by Molkobain** [comment]
You're right, PR updated with the placeholder fixed. Thanks

**Comment by Molkobain** [comment]
PR closed as I did another one cleaner.

**Comment by Molkobain** [comment]
PS : If you can delete it, do it. I can't.

**Pull request closed without merging**
