### PR TITLE
fix: Sort variables to avoid bad replacement in text

### LINKED ISSUE #1503: [Scene] Bad variable management when one variable id contains another id variable
**Describe the bug**
When you use the variable system in Scene (for example Send a message), if there are two variables with almost the same id, it creates an error.

For example, if you have these 2 variables:
-` 1. 1. data.main.temp`
-` 1. 1. data.main.temp_min`
 
And you fill text with "Hello {{ 1. 1. data.main.temp_min }}", the system will first replace `1. 1. data.main.temp` by a variable (and will let the `_min`) and so it's not the expected variable

**To Reproduce**
Create a scene where you fetch in HTTP `https://api.openweathermap.org/data/2.5/weather?lat=44.842680&lon=-0.586846&appid=KEY&lang=FR&units=metric`

**Screenshots**

image
image

**Your Gladys installation (please complete the following information):**

- Raspberry Pi 4 installation + SSD

### PR DESCRIPTION
**Pull request by cicoub13**
Fix #1503

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [x] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
It breaks the order of displayed variables

https://community.gladysassistant.com/t/etre-capable-dinjecter-une-variable-dans-requete-http-controler-un-appareil/7045/26?u=pierre-gilles

**Comment by VonOx** [comment]
Not stale

**Comment by Pierre-Gilles** [comment]
@cicoub13 Any news on this PR ? :)

**Comment by cicoub13** [comment]
Should be good now. I only use the sorted array as temporary variable for text replacement.
Tested locally and on my Gladys instance.

**Review by Pierre-Gilles — APPROVED** [review]
Looks good! Works on my side

**Pull request merged**
