### PR TITLE
WIP - Expand icon selection scenes and create icon groups

### PR DESCRIPTION
**Pull request by Terdious**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front ~~/server)
- [x] Is the linter passing? (`npm run eslint` on both front ~~/server~~)
- [x] Did you run prettier? (`npm run prettier` on both front ~~/server~~)
- [ ] ~~If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] ~~If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- [ ] ~~If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com)~~.
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

The purpose of this PR is a proposal to modify the "/dashboard/scene/new" view with the enlargement of the icon selection window as well as the creation of icon classification groups to better visualize and find them.

In full computer screen:
image

On a small computer screen:
image

On mobile:
image

### CODE REVIEW

**Comment by Terdious** [comment]
Visually it gives
- In list view (by default - like now):
image

- In group view:
image
image
image

**Comment by VonOx** [comment]
Hell yeah, very good ux improvment !

**Comment by Terdious** [comment]
Thank you very much @VonOx.

   @Pierre-Gilles , @VonOx , the server side error is obviously from a security issue. Should I do an npm audit as listed here? :
image

Or should I do a "Fetch upstream and merge on my branch?
image

Thanks in advance

**Comment by VonOx** [comment]
Yes all PR are concerned, I think we will manage security update on a separate PR

@atrovato made one #1499

**Comment by VonOx** [comment]
@Terdious #1499 is merged

**Comment by Terdious** [comment]
Thx @VonOx !!^^

**Comment by Terdious** [comment]
Hello @Pierre-Gilles and @VonOx,

Sorry to bother you again, but I don't understand the codecov error that appeared:
image

Could you tell me more? This is following the last merged update.

Thanks in advance.

**Comment by VonOx** [comment]
@Terdious codecov upload not working 😑 ,I will check today ( my PR's also concerned)

Not your fault 😉

**Comment by VonOx** [comment]
@Terdious seems to be ok now

**Comment by Terdious** [comment]
Yes it's good !! Thank you very much @VonOx for your information !!

**Pull request closed without merging**
