### PR TITLE
Adding footer, version and links in front

### PR DESCRIPTION
**Pull request by VonOx**
Screenshot

http://i.imgur.com/N1HjUPo.jpg

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Thanks for the PR, I just saw it ! I will give a look this week :)

**Comment by VonOx** [comment]
Yeah no problem.

FYI , i have followed an issue from adminlte repo ( https://github.com/almasaeed2010/AdminLTE/issues/88#issuecomment-68607690 ) to implement the footer ( not supported in V1.X )

**Comment by Pierre-Gilles** [comment]
Very nice, looks great :)

**Comment by Pierre-Gilles** [comment]
I'll just add "var" before defining a variable  ( ex : `var fs = require('fs');` ), it's cleaner.

**Pull request merged**
