### PR TITLE
Settings page to manage services

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- [x] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

New settings page to manage services.

image

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Really nice! :D 

On your screenshot, what's "Issued" ? Issued = publié in french ? I don't understand the state

**Comment by atrovato** [comment]
You're right, it should be "trouble"? Or do you suggest something?

It's when service start method throw an error, but I have to separate error from config, and error from service.

**Comment by atrovato** [comment]
I fact, `Issues` is ok, but not `Issued`.

**Comment by Pierre-Gilles** [comment]
That will do the job! :) 

Sorry for the slow answer, with the release of Gladys 4 I now have multiple pages of Github notifications ^^

**Review by Pierre-Gilles — CHANGES_REQUESTED** [review]
Thanks for your PR !

I just tested it, it looks sick :) 

One small feedback, here is what I see on my local instance when testing the PR: 

Screenshot 2020-11-20 at 16 09 58

Many integrations are displayed as "problèmes"

I was like "Oh are they broken? what's wrong?" 

There were not broken, just not configured.

Could we display a different message when a "ServiceNotConfigured" error is thrown by a service?

**Comment by atrovato** [comment]
That's a good point, I'll add a new "NOT_CONFIGURED" status.

**Comment by Pierre-Gilles** [comment]
Thanks for the PR! 

Merged in https://github.com/GladysAssistant/Gladys/commit/5b42a0697b0fa6f4b3cd94592e0bed66da42341e

I changed the translations because of 2 things: 

- "Mal configuré" => "Non configuré". It's not bad that a service is not configured, it's just the user is not using it. The wording was misleading.
- removed "please check logs" => We don't promote logs checking in Gladys 4. On the forum, we sometimes ask for logs for bug-checking with users who have very weird bugs / or to work with active community members on improving the product, but the UI of the product itself is for people, not developers. My mom have no idea what are logs! ^^

**Pull request closed without merging**
