### PR TITLE
Cypress tests

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Comment by atrovato** [comment]
Hi, for now, on login page is tested, for error and success cases.
Here some feedback: https://docs.google.com/document/d/1VXJHENNGTYVgn9PI8hOI-t_24YWPSHucfAnO0jwhTec/edit?usp=sharing 

cypress

**Comment by atrovato** [comment]
Signup process almost fully tested.
Preference and house pages not checked.

Language managed with process.env.LANGUAGE, default is 'fr' (expected english errors not set).

Next step, add an integration example, with mocked calls.

**Comment by Pierre-Gilles** [comment]
It looks really good! Congrats on the work here :)

**Comment by atrovato** [comment]
Ping!
What's new?
 - now starts front and server
 - creates default user / house and room
 - creates some commands to re-use login checks / methods
 - uses mocks for some cases
 - ordering tests (see constraints below)

I tested:
 - sign-up flow, with mandatory user fields
 - bluetooth page with "no bluetooth warning" (with real server, bluetooth is disabled)
 - bluetooth page without "no bluetooth warning" (with mock server, bluetooth is enalbed)

Constraints:
 - sign-up test should be run first, while DB is empty, if you run it not as 1st test, it will fail

CI not included here, but in another PR:
 - https://github.com/atrovato/Gladys/pull/7/commits/3cfebaf14fb15a6a96afe8278f90a61762c3fb7a
 - https://github.com/atrovato/Gladys/actions/runs/668470799

**Comment by atrovato** [comment]
Ok I think this is enough for the basics.
Now the question is: how to ensure each new code is well covered?
I look for a coverage plugin with cypress, but not so simple (for now).

**Comment by Pierre-Gilles** [comment]
So, as we discussed, do you think it's mature enough to merge this as a v1 of Cypress testing? :) 

If yes, can your remove the "draft" on the PR ? :)

**Review by Pierre-Gilles — APPROVED** [review]
Thank you very much for this PR!! 🙏🚀

**Pull request merged**
