### PR TITLE
Fix security audit

### PR DESCRIPTION
**Pull request by VonOx**
[pull] master from GladysAssistant:master### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Comment by VonOx** [comment]
I'm waiting for https://github.com/mapbox/node-sqlite3/issues/1483
https://github.com/mapbox/node-sqlite3/issues/1479
https://github.com/mapbox/node-sqlite3/issues/1493

**Comment by Pierre-Gilles** [comment]
I think we'll have to disable security audit in the meantime, because this security issue has no real impact on Gladys on this blocks all merge right now:

(see some of the report: https://www.npmjs.com/advisories/1780, it's a "high" severity in some case, not really in Gladys usage of this sub-sub-sub library)

**Comment by VonOx** [comment]
I agree to disable auudit.

**Comment by Pierre-Gilles** [comment]
I've set the audit to pass on "critical" security issues only while those dependencies are getting updated.

When they are, I'll put back to "high".

**Comment by VonOx** [comment]
Ok I will check status on sqlite3 side and push to high in this MR when fixed/updated

**Comment by VonOx** [comment]
About sqlite3 @Pierre-Gilles ,vscode guys published a fix. Due to the severity (and lack of patch in mapbox version), it's seems really more safe to switch to vscode version.

https://github.com/microsoft/vscode-node-sqlite3

What do you think ?

**Comment by Pierre-Gilles** [comment]
Let's see how it goes, I'm not a big fan of jumping on the first fork for the sake of making vulnerability check passes :) 

I don't see any risk for Gladys users in the current vulnerability, it's a dependency of a devDependency of sqlite3 right?

The "risky" dependency is "tar": 

sqlite3@5.0.2 ➔ node-gyp@3.8.0 ➔ tar@2.2.2

So it's dependency that is only called during the build process of the Docker image? I don't see any risk at this stage

**Comment by VonOx** [comment]
Ok , as non blocking for now , i close

**Pull request closed without merging**
