### PR TITLE
Cypress coverage

### PR DESCRIPTION
**Pull request by atrovato**
Add cypress coverage on codecov report.

@Pierre-Gilles we have many work to do!

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Nice! Is there a way to better separate front coverage from back coverage?

The codecov message merge the two coverage and it looks like Gladys has a code coverage of only 60% without really knowing which coverage we are talking about :)

Screenshot 2021-08-09 at 10 23 42

**Comment by atrovato** [comment]
Thank for feedbacks.
I'll take a look for this point.

**Comment by atrovato** [comment]
@Pierre-Gilles 
I can propose this
image

**Comment by Pierre-Gilles** [comment]
@atrovato Ok! Looks way better than before 🙂 On GitHub checks it'll be separate right ? 

So we still keep our rules on backend coverage change ?

**Comment by atrovato** [comment]
I'll try removing some server tests to check for coverage check to fail.

**Comment by atrovato** [comment]
Ok, you were right to ask for this point, coverage check is not applied anymore on server side.
Work again on it 😄

**Comment by atrovato** [comment]
@Pierre-Gilles according to latest coverage, it looks good.

image

Once it's ok for you, I will revert "test deletion" commit.

**Comment by Pierre-Gilles** [comment]
@atrovato 

The comment coverage still seems to mix both coverage:

Screenshot 2021-10-09 at 15 52 20

(I check, it's the coverage from 3 days ago)

You know if there is a way to get a notification message with only backend / or backend-front separated ?

**Comment by atrovato** [comment]
Oww I didn't try this way.
Coverage are separated by flags, details on bottom table.

@VonOx can you help me to find a better way here?

**Comment by VonOx** [comment]
@atrovato I'm working on

Maybe try with this codecov.yml

```yml
coverage:
  status:
    project:
      default:
        target: 90% #overall project/ repo coverage
      front:
        target: 60%
        flags:
          - front
      server:
        target: 90%
        flags:
          - server

# adding Flags to your `layout` configuration to show up in the PR comment
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null

# New root YAML section = `flags:`
# This is where you would define every flag from your
# uploader, and update when new Flags added

flags:
  front:
    paths:
      - front
    carryforward: true
  server:
    paths:
      - server
    carryforward: true
```

**Comment by atrovato** [comment]
Thanks @VonOx 
1st try currently building 🤞

**Comment by atrovato** [comment]
@VonOx there is still only one report, one codecov comment... both front and server are still mixed.

**Comment by VonOx** [comment]
I will merge your pr in my CI test repo, keep you updated

**Comment by VonOx** [comment]
Codecov use only one comment, diff is global

But flags are working

https://github.com/VonOx/gladys-ci/pull/9#issuecomment-970697463

I think we need a master test to have a working diff ( codecov need a base to compare)

**Comment by atrovato** [comment]
Thanls, I was already working with flags, but it looks it didn't please to Pierre-Gilles.

And do you think you can try with coveralls to compare multi-report / flag comment?

**Comment by VonOx** [comment]
> And do you think you can try with coveralls to compare multi-report / flag comment?

Yep , no problem.

**Comment by atrovato** [comment]
Not stale!

**Comment by atrovato** [comment]
Stale...
It will be back...

**Pull request closed without merging**
