### PR TITLE
Fix incorrect attribute

### PR DESCRIPTION
**Pull request by atrovato**
Something weird in dashboard boxes.
Some use `feature.last_value`, some uses `feature.lastValue`...

Did I miss something?
Or this fix looks good?

(searched all `lastValue` occurrences and replace with `last_value`)

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
I'm quite surprised, it seems you're right but I can't understand why it's working right now... (or maybe it's not working!)

@VonOx I think you coded the MultiLevel no? any idea?

**Comment by Pierre-Gilles** [comment]
Indeed, @VonOx you coded the Brightness box: 

https://github.com/GladysAssistant/Gladys/pull/1082/files#diff-91ffef4861a07c96af49b03dbbba5c76e5f0d2826031cbd119642cec2eb5a3a3R13

Is it working or did you code it blindly?

**Comment by Pierre-Gilles** [comment]
From my test, it seems you're right @atrovato, it's broken right now.

**Comment by VonOx** [comment]
Yeah it works, but weirdly right now.

Slider is always at 50% when I switch light on and when I slide the button sometimes it stuck.

I have implemented brightness based on multi level but tested with my own devices.

I can't explain the behavior... Sorry

**Comment by Pierre-Gilles** [comment]
It works to control devices, but the slider is always at 50% (because lastValue doesn't exist). I investigated, it never worked. 

but @atrovato, I don't think your PR solves the issue. I have a feeling the slider component never worked, even with the right variable. It needs a little bit of work to understand how to make the slider component work.

Thanks for finding this Alex!

**Comment by VonOx** [comment]
Brightness on my lights physically change so this is weird.

**Comment by Pierre-Gilles** [comment]
@VonOx nothing weird, the control works indeed, it's the display which is broken

**Comment by VonOx** [comment]
> @VonOx nothing weird, the control works indeed, it's the display which is broken

Ok did'nt understand, my bad.

**Comment by Pierre-Gilles** [comment]
@atrovato My bad, your PR solves the issue!

**Review by Pierre-Gilles — APPROVED** [review]
It works on my side! Thanks!

**Comment by atrovato** [comment]
I just read all... quite funny :)

**Pull request merged**
