### PR TITLE
Z2m cover feature

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Linked to 
 - #1541
 - #1574
 - #1543 

Manage cover with z2m.

### CODE REVIEW

**Comment by VonOx** [comment]
Patched my production server to test with my device
front builded after patch, container restarted

image

discover json 
```json
  {
    "name": "Volet chambre Sasha",
    "model": "CCT5015-0001",
    "external_id": "zigbee2mqtt:Volet chambre Sasha",
    "features": [
      {
        "name": "State",
        "min": -1,
        "read_only": false,
        "has_feedback": true,
        "category": "shutter",
        "type": "state",
        "max": 1,
        "unit": null,
        "external_id": "zigbee2mqtt:Volet chambre Sasha:shutter:state:state",
        "selector": "zigbee2mqtt-volet-chambre-sasha-shutter-state-state"
      },
      {
        "name": "Position",
        "min": 0,
        "read_only": false,
        "has_feedback": true,
        "category": "shutter",
        "type": "position",
        "unit": "percent",
        "max": 100,
        "external_id": "zigbee2mqtt:Volet chambre Sasha:shutter:position:position",
        "selector": "zigbee2mqtt-volet-chambre-sasha-shutter-position-position"
      }
    ],
    "should_poll": false,
    "service_id": "0fccf6a6-0377-4678-b244-30d650619a42"
  }
```
Attempt to save
image

Not sure how I can help ( no log in server and no log in front )

-------------------------------

I'va added the device manually in db

image

Button not working, level feature does.

**Comment by VonOx** [comment]
@atrovato If it help

```
2022-08-03T14:34:20+0200 <error> handleMqttMessage.js:97 () Failed to convert value for device Volet chambre Sasha: Error: Zigbee2mqqt don't handle value "OPEN" for property "state".
    at Zigbee2mqttManager.readValue (/src/server/services/zigbee2mqtt/lib/readValue.js:22:11)
    at /src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:93:31
    at Array.forEach (<anonymous>)
    at Zigbee2mqttManager.handleMqttMessage (/src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:86:41)
    at MqttClient.<anonymous> (/src/server/services/zigbee2mqtt/lib/connect.js:53:12)
    at MqttClient.emit (events.js:400:28)
    at MqttClient._handlePublish (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:410:12)
    at work (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by atrovato** [comment]
@VonOx don't you miss a commit?
I paste your payload in the demo mode, and I have a better display

image

I think you forgot both 8dc71030d27097cea2d198b99718379378e47af2 and 8f81ccc08a886e771e76e918dbca72644c8a2245 commits (https://github.com/GladysAssistant/Gladys/pull/1576/commits).

**Comment by atrovato** [comment]
Read again, softly, I agree there is another problem.

**Comment by VonOx** [comment]
I don't think so, I used a patch file. 🤔

I will manually check every file tomorrow.

**Comment by atrovato** [comment]
I pushed a new commit on z2m part, for the "readValue" error.
Please add 44c105d0ee27e02070a411795fcfd6af3e3f5332 commit too.
And keep crossed fingers ;)

**Comment by VonOx** [comment]
I've applied commit

Not working, and no error in logs for button.

But position throw error. ( the slider is working )

```
2022-08-04T09:26:07+0200 <error> handleMqttMessage.js:97 () Failed to convert value for device Volet chambre Sasha: Error: Zigbee2mqqt don't handle value "35" for property "position".
    at Zigbee2mqttManager.readValue (/src/server/services/zigbee2mqtt/lib/readValue.js:24:11)
    at /src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:93:31
    at Array.forEach (<anonymous>)
    at Zigbee2mqttManager.handleMqttMessage (/src/server/services/zigbee2mqtt/lib/handleMqttMessage.js:86:41)
    at MqttClient.<anonymous> (/src/server/services/zigbee2mqtt/lib/connect.js:53:12)
    at MqttClient.emit (events.js:400:28)
    at MqttClient._handlePublish (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:410:12)
    at work (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/src/server/services/zigbee2mqtt/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/src/server/services/zigbee2mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

Trying to edit the device ouput this error on front
image

**Comment by atrovato** [comment]
This constant is in a server file `server/utils/constants.js`.
Did you copy it too?

I just rebase from #1576 branch (which was just rebased from latest merged changes on master branch).

**Comment by atrovato** [comment]
Tests in progress (I hope): https://community.gladysassistant.com/t/gestion-des-volets-roulants/5693/54?u=alextrovato

**Comment by VonOx** [comment]
It's working now !

Animation

**Comment by Pierre-Gilles** [comment]
Nice ! Can I merge ?

**Comment by VonOx** [comment]
Yes no error with my device

**Comment by atrovato** [comment]
I just rebase on master. Thanks @VonOx

**Review by Pierre-Gilles — APPROVED** [review]
Amazing work, thanks @atrovato 🙏

**Pull request merged**
