### PR TITLE
chore: Add node/npm engines in package.json

### PR DESCRIPTION
**Pull request by cicoub13**
https://docs.npmjs.com/cli/v6/configuring-npm/package-json

After discussion https://community.gladysassistant.com/t/fresh-development-installation/5785

### CODE REVIEW

**Comment by VonOx** [comment]
Not sure if this help because no warning is produce and user can run anything ( Maybe I'm wrong ? )

**Comment by cicoub13** [comment]
> Not sure if this help because no warning is produce and user can run anything ( Maybe I'm wrong ? )

You're right, no warning but developers can now easily which version of node/npm to use. If you think documentation (https://gladysassistant.com/fr/docs/api/setup-development-environnement) is enough, I'll close this PR.

There is one way to force node version, it's by adding a `preinstall` script in `package.json` that checks version. But I find it too restrictive.

**Comment by VonOx** [comment]
> You're right, no warning but developers can now easily wich version of node/npm to use. If you think documentation (https://gladysassistant.com/fr/docs/api/setup-development-environnement) is enough, I'll close this PR.

No , I'm just asking ;)

> I find it too restrictive.

I agree

**Review by Pierre-Gilles — APPROVED** [review]
Good idea!

**Comment by Pierre-Gilles** [comment]
@all-contributors please add @cicoub13 for code

**Pull request merged**
