### PR TITLE
Changed the functioning of feature names for mqtt and tasmota in the charts legend 

### PR DESCRIPTION
**Pull request by Terdious**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Changed the functioning of feature names for mqtt and tasmota in the curves legend and for tasmota on the dashboard.
Avant : 
image
image

Après :
image
image

### CODE REVIEW

**Comment by Terdious** [comment]
@Pierre-Gilles

**Comment by atrovato** [comment]
Hi @Terdious,
it doesn't look bad, but 2 things:
1. are we sure we want to do this? it's a simple question, but I would prefer to be sure of the need
2. the change on `front/src/utils/device.js` file will change also the dashboard device box

To me it's nice, but let's talk to the big boss ;)

**Comment by atrovato** [comment]
For this point, some of us discuss about a generic way, not based on service name, and there is a dev on my personal Github (https://github.com/atrovato/Gladys/pull/54).

**Comment by Terdious** [comment]
Following the release of v4.12 which implements this feature, no longer needed

**Pull request closed without merging**
