### PR TITLE
Add French translation + i18n checker

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/gladys-4-docs) and the [website](https://documentation.gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Comment by atrovato** [comment]
I also fixed hard code messages.
Maybe we can merge it with only 'en' language, then add 'fr' when it is in progress?

**Comment by atrovato** [comment]
A json comparator is added to check all intragations are correctly translate.

**Comment by atrovato** [comment]
Calendar page is missing for translation, but I suppose it will change in the future, so I wait until it is usable.

**Comment by NickDub-old** [comment]
What about the server side?
For example for the feature names (server/config/i18n/xx.json).

**Comment by atrovato** [comment]
@NickDub it looks like i18n is never used in server side. I removed it.

**Comment by Pierre-Gilles** [comment]
Thanks for your amazing work, this PR was really great !! 😄 

I spent the day improving translations & making the app work in french. 

It's live in master, merged in https://github.com/GladysAssistant/Gladys/pull/771

Thanks again for your work 👏

**Pull request closed without merging**
