### PR TITLE
Feat zigbee2mqtt usb change

### LINKED ISSUE #1887: [Zigbee2Mqtt] Changing Dongle port requires deactivation/reactivation of service to be taken in account
**Describe the bug**
When Zigbee2Mqqt is already initialized (docker containers created), changing the dongle port in Parameters is not taken in account until user restarts the containers (by going into Configuration and turning off then on the service).

https://community.gladysassistant.com/t/zigbee2mqtt-et-synology-ds920-en-7-2-probleme-suite-upgrade-synology/

**Expected behavior**
When user clicks on Save in Parameters page, Gladys should check if port has changed and trigger automatically a redeployment.

### PR DESCRIPTION
**Pull request by cicoub13**
Fixes #1887

Adding a system.inspectContainer(containerId) was needed to compare Devices[0].PathOnHost

Under testing in real use cases

### CODE REVIEW

**Review by Pierre-Gilles — DISMISSED** [review]
Looks good to me, but I think we should have more real world testing on this!

**Review by Pierre-Gilles — COMMENTED** [review]
What is those files in the PR?

Screenshot 2023-10-20 at 14 33 27

**Comment by cicoub13** [comment]
> What is those files in the PR?

They are coming from an interrupted test. I removed them and added to `.gitignore`

**Review by Pierre-Gilles — APPROVED** [review]
Thanks for the PR! 🙏

**Pull request merged**
