### PR TITLE
Make installation of services mandatory to install Gladys

### PR DESCRIPTION
**Pull request by atrovato**
Make installation of services mandatory to install Gladys

### CODE REVIEW

**Review by VonOx — DISMISSED** [review]
I'm ok , as cypress run need server to start, OZW need to be setup before npm install

**Comment by Pierre-Gilles** [comment]
I'm good with this PR! 

Could you integrate this: https://github.com/GladysAssistant/Gladys/pull/1362/files

In this PR so I merge one for the whole "make service installation mandatory" thing?

**Comment by atrovato** [comment]
@Pierre-Gilles commit added to this PR ;)

**Comment by atrovato** [comment]
@Pierre-Gilles ok looks ready now...

**Review by Pierre-Gilles — APPROVED** [review]

**Review by Pierre-Gilles — APPROVED** [review]

**Pull request merged**
