### PR TITLE
Docker build on PR via GitHub actions

### LINKED ISSUE #626: Generate service image for testing
Add the possibility to generate a docker image on a PR branch to allow the community to test it easily.

Maybe based on a git tag (`testing-service-myservice`) ?

### PR DESCRIPTION
**Pull request by VonOx**
This resolve #626 by providing docker build on PR by using Github Actions

After successful build, PR is commented with docker command to test the image

You need to set Github Secrets in the repo for pushing image to dockerhub:
* DOCKER_PASSWORD
* DOCKER_USER

Configured for dockerhub repo named gladys-dev

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Wow! Really nice! 👏

**Comment by VonOx** [comment]
I've made modification related to OZW build.
This can now be merged

**Comment by Pierre-Gilles** [comment]
Thanks for this great PR ! First PR building here:

https://github.com/GladysAssistant/Gladys/pull/808/checks?check_run_id=685353843

**Comment by Pierre-Gilles** [comment]
Mmm seems the login failed 

Screenshot 2020-05-18 at 15 11 25

yes, I did put the secrets:

Screenshot 2020-05-18 at 15 12 43

Did this work on your repo?

**Comment by VonOx** [comment]
Yeah its working fine on my repo https://github.com/VonOx/Gladys4_GithubActions

EDIT: I think secrets must be at repo level not organization. 
Or maybe access policy behavior ?
https://github.blog/changelog/2020-05-14-organization-secrets/

**Comment by Pierre-Gilles** [comment]
It's supposed to be ok, I put only the Gladys repo: 

Screenshot 2020-05-18 at 17 16 46

I started another PR to see if it works =>

https://github.com/GladysAssistant/Gladys/pull/783/checks?check_run_id=685812996

**Comment by Pierre-Gilles** [comment]
One question: how is it different from CircleCI? Are secret shared with third-party pull request?

How is it safer that what we couldn't do with CircleCI?

**Comment by Pierre-Gilles** [comment]
From what I found, it seems it's not possible to use secrets in Github Actions from PR =>

https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/td-p/30678

So this doesn't work

**Comment by Pierre-Gilles** [comment]
Sadly it's broken on your repo as well :/

https://github.com/VonOx/Gladys4_GithubActions/pull/16

**Comment by Pierre-Gilles** [comment]
Screenshot 2020-05-18 at 17 40 54

**Comment by VonOx** [comment]
F**k! I've made several PR to test, but forking his own repo is not possible.

**Comment by VonOx** [comment]
Back to square one !

Github Actions and CircleCI have the same behavior on Fork . The risk is important for any CI system.

I've no solution for now 😞

**Comment by Pierre-Gilles** [comment]
ok ! I'll remove the Github actions on master then

**Pull request merged**
