### PR TITLE
Oauth2 client

### PR DESCRIPTION
**Pull request by euguuu**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change
this PR contains only oauth2 client common code for any oauth2 authentification external request

the goal is to provide generic api to call external oauth2 authentication service (generic server api call and generic form for front)

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Hello! What's the final use case for this PR ?

**Comment by euguuu** [comment]
the final use case is to add withings device integration (I separate this PR and withings PR to do a small PR) 
I have a withings inegration ready (I just need to add cypress test now to do another PR), I need your comment on this PR to integrate changes you want
(is same PR than #1192)

**Comment by Pierre-Gilles** [comment]
Does this needs that Gladys is exposed on the internet ?

**Comment by euguuu** [comment]
no it's gladys to call an external platform

**Pull request closed without merging**
