### PR TITLE
Philips hue model LOM002

### PR DESCRIPTION
**Pull request by Terdious**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/gladys-4-docs) and the [website](https://documentation.gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change
Add model LOM002 Hue Smart plug
https://community.gladysassistant.com/t/philips-hue-accessoires/5339/3?u=terdious

### CODE REVIEW

**Comment by Terdious** [comment]
For the check "Is the linter passing? (npm run eslint on both front/server)", i have : 
```
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 2.02 KiB | 344.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/Terdious/Gladys.git
   99cf29b6..3f5cb5d3  Philips-Hue-L0M002 -> Philips-Hue-L0M002
~\Gladys-Master-Philips Hue\Gladys\server [Philips-Hue-L0M002]> npm run eslint

> gladys-server@ eslint C:\Users\tlemaistre\Documents\Gladys\Gladys-Master-Philips Hue\Gladys\server
> eslint .


Gladys-Master-Philips Hue\Gladys\server\services\usb\api\usb.controller.js
  13:17  warning  Unexpected unnamed function  func-names

Gladys-Master-Philips Hue\Gladys\server\services\zwave\index.js
  7:25  error  Unable to resolve path to module 'openzwave-shared'  import/no-unresolved

Gladys-Master-Philips Hue\Gladys\server\test\benchmark\triggers.js
  61:8  warning  Unexpected constant condition  no-constant-condition

Gladys-Master-Philips Hue\Gladys\server\test\lib\gateway\GladysGatewayClientMock.test.js
  4:33  warning  Unexpected unnamed function  func-names

✖ 4 problems (1 error, 3 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gladys-server@ eslint: `eslint .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gladys-server@ eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tlemaistre\AppData\Roaming\npm-cache\_logs\2020-05-09T10_50_57_375Z-debug.log
```
For 
```
> gladys-server@ prettier C:\Users\tlemaistre\Documents\Gladys\Gladys-Master-Philips Hue\Gladys\server
> prettier --write '**/*.js' '**/*.json'

[error] No matching files. Patterns tried: '**/*.js' '**/*.json' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gladys-server@ prettier: `prettier --write '**/*.js' '**/*.json'`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gladys-server@ prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tlemaistre\AppData\Roaming\npm-cache\_logs\2020-05-09T10_59_17_546Z-debug.log
```
Is this normal?

**Comment by VonOx** [comment]
npm run test on linux:

Fail for Front but not related to this PR

Initial Test of the Header
    ✕ Header renders Gladys Assistant title and 8 items in header (4ms)
    ✕ Should return null, login page doesnt need a header (1ms)
    ✕ [Backslash URL] Header renders Gladys Assistant title and 8 items in header
    ✕ [Backslash URL] Should return null, login page doesnt need a header (1ms)

**Comment by Terdious** [comment]
Hey @VonOx,

I saw your message and that you had tested the code, but suddenly I admit that I did not understand ^^ Do I have to do something in particular? How can I have a problem in the forehead without having touched it?

For my part, I tested to redo everything under my RaspPi, and I find myself again with fail but different test. I don't understand anything, I don't touch anything else:

```
  752 passing (6m)
  1 failing

  1) POST /api/v1/message
       should send message:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/pi/Philips-Hue/Gladys/server/rollers/message/message.test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)



npm ERR! Test failed.  See above for more details.
pi@raspberrypiGladys-Dev:~/Philips-Hue/Gladys/server $
```

**Comment by VonOx** [comment]
> Do I have to do something

I don't think so but maybe @Pierre-Gilles can help us because I don't understand too 😞

**Comment by Pierre-Gilles** [comment]
>For my part, I tested to redo everything under my RaspPi, and I find myself again with fail but different test. I don't understand anything, I don't touch anything else:

Don't start tests on your pi, it's waay to slow, this is why you have this error ^^

**Comment by Pierre-Gilles** [comment]
Sinon, pour parler de cette PR, tes tests ne passent pas car tu n'as pas formatté ton code avec prettier! 

cf https://circleci.com/gh/GladysAssistant/Gladys/2636

Tu as un fichier qui est mal formatté: 

Screenshot 2020-05-25 at 10 59 36

Je te conseille d'utiliser VSCode + l'extension prettier + de configurer le "format on save" de ton IDE pour que le formattage soit automatique

**Comment by Terdious** [comment]
> Sinon, pour parler de cette PR, tes tests ne passent pas car tu n'as pas formatté ton code avec prettier!
> 
> cf https://circleci.com/gh/GladysAssistant/Gladys/2636
> 
> Tu as un fichier qui est mal formatté:
> 
> Je te conseille d'utiliser VSCode + l'extension prettier + de configurer le "format on save" de ton IDE pour que le formattage soit automatique

Merci beaucoup @Pierre-Gilles, en effet ça à l'air beaucoup mieux. 2 espaces oubliés après ":" !! My bad sorry !!
En effet j'avais bien eslint dans VSCode mais pas prettier. Et je n'avais pas activé le "format on save".

Dis moi si il y a autre chose à faire.

**Pull request merged**
