### PR TITLE
Upgrade philips-hue dependency to 4.0.9 & improve bridge search

### PR DESCRIPTION
**Pull request by Pierre-Gilles**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

### CODE REVIEW

**Comment by VonOx** [comment]
Not real test but its working with an emulated bridge.

image
image

Will test this week end with real hardware

**Review by VonOx — CHANGES_REQUESTED** [review]
API now return data on _data ( was _rawData )
https://community.gladysassistant.com/t/probleme-dintegration-philips-hue/6075/40?u=vonox

**Review by VonOx — APPROVED** [review]

**Review by atrovato — APPROVED** [review]
Trust you tested it with real devices.

**Comment by VonOx** [comment]
Yep tested on real hardware, @cicoub13 did too.

**Review by cicoub13 — APPROVED** [review]

**Pull request merged**
