### PR TITLE
z2m thermostat mangement

### PR DESCRIPTION
**Pull request by atrovato**
https://community.gladysassistant.com/t/thermostat-avec-zigbee2mqtt/7634/5?u=alextrovato

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Nice!! Is this ready for review? 

If yes, can you provide a Docker build for testers?

cc @LM1LC3N7

**Comment by LM1LC3N7** [comment]
Is there a docker build yet @atrovato?

**Comment by atrovato** [comment]
Here the docker image `atrovato/gladys:z2m-thermostat`

https://community.gladysassistant.com/t/thermostat-avec-zigbee2mqtt/7634?u=alextrovato

**Comment by LM1LC3N7** [comment]
Sorry for the delay! @atrovato I tried the image and to use the thermostat through a fake mqtt device.

Just to be clear, what do you want me to try?

For now:
1. Fake MQTT device created
2. Added to one dashboard. ✅ I can update the value from here. ❌ But I am not sure it is retained. A refresh of the dashboard display again an empty box without value.
3. From a scene, ✅ I can set a temperature using "control a device". ❌ But again, the value is empty by message or on the dashboard.

Screenshot_20230102-150743_Bromite

Screenshot_20230102-150650_Bromite
Screenshot_20230102-150703_Bromite
Screenshot_20230102-150724_Bromite
Screenshot_20230102-150631

**Comment by Pierre-Gilles** [comment]
@LM1LC3N7 This PR is related to Zigbee devices, not MQTT devices. Have you tried in the Zigbee2mqtt integration?

**Comment by LM1LC3N7** [comment]
Oh! Thanks for the clarification 😅

Yep definitely my zigbee smart valve are detected and I can control them!

Screenshot_20230102-190732
Screenshot_20230102-190931_Firefox Nightly

**Comment by atrovato** [comment]
I just rebased it, go for review :)

**Review by VonOx — DISMISSED** [review]
Looks fine :)

**Review by Pierre-Gilles — APPROVED** [review]
If it's working fine for everyone, I'm good for a merge 🙂

Thanks for the PR @atrovato, great work 👏

**Pull request merged**
