### PR TITLE
Z2M add soil moisture sensor

### PR DESCRIPTION
**Pull request by euguuu**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Just to add soil_moisture sensor for this device:
https://www.zigbee2mqtt.io/devices/TS0601_soil.html

the result in dashboard (tested with real device)
image

and in integration page
image

### CODE REVIEW

**Review by Pierre-Gilles — COMMENTED** [review]
Thanks for the PR! It looks nice :)

I think we should have a specific device feature for that, because the issue here is that Gladys will use this device for the box "Humidity in room", but "Room Humidity" != "Soil moisture"

We did the same for "CPU temperature" != "Room temperature"

What do you think?

**Comment by atrovato** [comment]
I agree, humidity and soil moisture are different kind of sensors in other home automation solutions.

**Review by Pierre-Gilles — APPROVED** [review]
Looks good to me!

**Comment by Pierre-Gilles** [comment]
@all-contributors please add @euguuu for code

**Pull request merged**
