### PR TITLE
🐳 Docker multiarch support

### PR DESCRIPTION
**Pull request by VonOx**
### Description of change

* Switch to LTS base image
* FIX typo in Dockerfile.arm32v7
* FIX missing `&&` in layer
* Build script creation for multiarch images ( with manifest )
* Removed useless comment in Dockerfiles and improve readability

### Warning

Travis build is ok
Intel image works fine, but arm base image need to be tested in proper hardware before merging.

### CODE REVIEW

**Comment by VonOx** [comment]
Travis build fail, @Pierre-Gilles are you using email adress as username for docker login ?

https://travis-ci.org/GladysProject/Gladys/jobs/467539858#L575

**Comment by Pierre-Gilles** [comment]
@VonOx I don't think so, in Travis I have 2 variables: DOCKER_USERNAME and DOCKER_PASSWORD. I can't read the value, but I'm pretty sure it's my username and not the email.

I restarted the build to be sure :)

**Comment by Pierre-Gilles** [comment]
Ok failed... trying again and changing the username to be sure

**Comment by Pierre-Gilles** [comment]
Oh i understand! 

Travis env variables are not available for pull requests! :p 

Otherwise you would be able to get my password by console.log my passwords ^^

**Comment by VonOx** [comment]
Yeah that explain why build fail.

Work on my side 😉

**Comment by Pierre-Gilles** [comment]
Great! Amazing work btw! :) I just merged, should work on master.

It's gonna help a lot for the work on Gladys 4!

**Pull request merged**
