### PR TITLE
[WIP] D-Link DSP-W215 smart plug 🚧

### PR DESCRIPTION
**Pull request by PhilippeMA**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code) (NO CHANGE)
- If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/gladys-4-docs) and the [website](https://documentation.gladysassistant.com). (NO DOCUMENTATION NEEDED)
- Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com). (NOT NECESSARY)

At the moment, TODO list : 
- [x] Modify PIN at device creation
- [x] Test connection at device creation
- [x] Test connection button when editing device (done on may 2nd)
- [ ] Final code review

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Service to control DSP-W215 smart plug and read informations : state / temperature / power / energy (useful for scenes).

W215-init

DSPW215-example

### CODE REVIEW

**Comment by atrovato** [comment]
Don't we prefer we D-Link integration (not specifc to the DSP-W215 device) and in this overall D-Link integration, maybe a sub-tab for each specific devices.

I have a D-Link IP cam, I think I will arrive to develop something to integrate it into Gladys.

So I don't think to get a card in "integrations" menu for DSP-W215, one one D-Link IP-CAM, and more and more is a good solution.

**Comment by PhilippeMA** [comment]
> Don't we prefer we D-Link integration (not specifc to the DSP-W215 device) and in this overall D-Link integration, maybe a sub-tab for each specific devices.
> 
> I have a D-Link IP cam, I think I will arrive to develop something to integrate it into Gladys.
> 
> So I don't think to get a card in "integrations" menu for DSP-W215, one one D-Link IP-CAM, and more and more is a good solution.

@atrovato, What do you think about this presentation : 
DLink-abstract-implementation

Or, i should abstract the devices list ? Specific fields conditioned by "model".

**Comment by atrovato** [comment]
I think it's a good start. Maybe we will need to change according to incoming feature, but I think it's enough at this time.
And I suppose you changed hard written file and folder names to `dlink` ;)

**Comment by PhilippeMA** [comment]
> And I suppose you changed hard written file and folder names to `dlink` ;)

Ahah, no, not yet, but I had it in mind.

**Pull request closed without merging**
