### PR TITLE
Bluetooth stop presence scanner

### PR DESCRIPTION
**Pull request by atrovato**
### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Disable bluetooth scanner presence on BLE connection lost.

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Thanks for your PR! 

Does it block someone who want to start a bluetooth scan with the bluetooth state != poweredOn ?

I don't see any change in the `bluetooth.scan.js` ?

**Comment by atrovato** [comment]
You're right, I now add the state checker on scan process. This will now throw an error with "invalid BLE state" message.

**Comment by Pierre-Gilles** [comment]
Nice! Looks better to me :) 

What does the user see in the UI if he tries to scan but the Bluetooth is not ready? Is there a proper error message so the user is not lost ?

**Comment by atrovato** [comment]
Sorry for late answer.
If the Bluetooth is disabled, in UI, a warning panel is displayed, and buttons are disabled.

**Review by Pierre-Gilles — APPROVED** [review]
Just tested locally, and it works fine! Thank you for this PR 🙏

**Pull request merged**
