### PR TITLE
[TAMOSTA] Manage distance sensor

### LINKED ISSUE #1017: [TAMOSTA] Error 500 MQTT Discover
@atrovato I've a tamosta device up and running publishing on MQTT container configured in MQTT Service.

When I try to discover Tamosta device in MQTT 
image

Gladys UI retrun generic error
`Error discovering Tasmota devices.`

Nothing in server logs :/

### LINKED ISSUE #1020: [TAMOSTA] Add ultrasonic sensor SR04

### PR DESCRIPTION
**Pull request by atrovato**
Fixes #1020 

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Add Tasmota distante sensor.

### CODE REVIEW

**Comment by VonOx** [comment]
Tested your PR right now:

Discover OK
image

And of course dashboard ok:
image

**Comment by Pierre-Gilles** [comment]
Sorry obviously there is a conflict as I merged the other PR in between 😅

**Comment by atrovato** [comment]
Yes, I fixed it now ;)

**Review by Pierre-Gilles — APPROVED** [review]
Good for me! Thanks again for this 👏

**Pull request merged**
